### ISSUE TITLE
Test progress reporting

### ISSUE THREAD

**Issue by rundis** [elm-community/elm-test#10]
I haven't worked enough with larger elm apps to know if this is even a point. But if tests take a while to run it would be really cool if one could subscribe to test progress in some fashion.

A few editors like Atom, Visual Studio Code and Light Table comes bundled with a node instance (electron), maybe that opens up possibilities to allow such a feature to be more feasible. Maybe one could subscribe to a port that a runner puts messages to (start, suite start, test result, suite end, end etc)

**Comment by eeue56** [comment]
Tooling support is coming in a new version of elm-test
