### ISSUE TITLE
Fuzzer confused by float division

### ISSUE THREAD

**Issue by j-panasiuk** [elm-community/elm-test#100]
So this one is very curious. I define custom fuzzer generating `Box` with **size** value ranging from 100 to 199. And it works as expected... until in my fuzz test I convert it to float and use division on it. Then the fuzzer takes the liberty of going out of its range and checking 0. Which in my case lead to division by zero out of nowhere
```elm
import Test exposing (..)
import Expect
import Fuzz exposing (Fuzzer)
import Random.Pcg as Random exposing (Generator)
import Shrink exposing (Shrinker)


type alias Box =
    { size : Int }


test : Test
test =
    describe "box"
        [ fuzz box "should not get zeros here, because range is 100-199" <|
            \{ size } ->
                Expect.equal 0 ((toFloat size) / (toFloat size))
        ]



box: Fuzzer Box
box =
    let
        generator : Generator Box
        generator =
            Random.map Box (Random.int 100 199)

        shrinker : Shrinker Box
        shrinker { size } =
            Shrink.map Box (Shrink.int size)
    in
        Fuzz.custom generator shrinker
```
For me this fails ~100% of the time with:
```
↓ box
✗ should not get zeros here, because range is 100-199

Given { size = 0 }
For me this fails ~100% of the time
    NaN
    ╷
    │ Expect.equal
    ╵
    0

```
It looked spooky to me, but it seems to only affect failed tests, so it must be a problem with the shrinker. In this case it's just very misleading, as it points to values it shouldn't be generating. After looking into shrinkers a bit, it seems to be a non-issue.

**Comment by mgold** [comment]
The shrinker doesn't know about the restrictions placed on `Random.int`. Use `Fuzz.intRange 100 199 |> Fuzz.map Box` instead.

**Comment by j-panasiuk** [comment]
Yes, that's what i just figured! However it only became clear after I actually wrote it down (rubber duck magic). Thanks!
