### ISSUE TITLE
Fuzz test failures counting as n failed tests

### ISSUE THREAD

**Issue by drathier** [elm-community/elm-test#103]
We're counting passing tests, but failing test runs. 

```
TEST RUN PASSED

Passed: 63
Failed: 0
```
and then break a single fuzz test:
```
TEST RUN FAILED

Passed: 62
Failed: 81
```

Could we either count failed test cases, or rephrase it somehow?

**Comment by rtfeldman** [comment]
This is a bug - should say `Failed: 1`

Thanks for pointing it out!

**Comment by rtfeldman** [comment]
@drathier I haven't been able to reproduce this locally; for me, even if I use a custom `Fuzzer` that performs no shrinking (leading to a ton of failures within the individual test), that whole thing is still counted as only 1 failure.

Can you post a [SSCCE](http://sscce.org/) reproducing this?

**Comment by drathier** [comment]
Pretty sure something's corrupt on my machine. Can't even run elm-test anymore, even after reinstalling both elm and elm-test.

```
 TypeError: testModule.worker is not a function
    at evalElmCode (C:\Users\drathier\AppData\Roaming\npm\node_modules\elm-test\bin\elm-test:178:24)
    at C:\Users\drathier\AppData\Roaming\npm\node_modules\elm-test\bin\elm-test:303:33
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

**Comment by rtfeldman** [comment]
@drathier any update on being able to reproduce this? Otherwise I'd rather close it for now and reopen if anyone encounters it again.

**Comment by drathier** [comment]
I can reproduce it locally using the elm-test elm-tests. It's on my todo list, probably done tomorrow.

**Comment by rtfeldman** [comment]
@drathier no rush, but still would like to reproduce this if possible. Not sure what the fix will be, but I'd like to include it in the next release.

**Comment by drathier** [comment]
Running elm-test in elm-test crashes with a runtime error for me. I remember now that this was the reason I wasn't able to reproduce this when I wrote that last comment. Do I need a newer version of the runner than the one available on npm?

```
$ elm-test
Success! Compiled 1 module.
Successfully generated C:\Users\drathier\AppData\Local\Temp\elm_test_117213-15984-1gir27s.xcu9pb9.js

TEST RUN PASSED

Passed: 81
Failed: 0

Exit code: 0
The test run failed because it encountered a runtime exception:

 TypeError: testModule.worker is not a function
    at evalElmCode (C:\Users\drathier\AppData\Roaming\npm\node_modules\elm-test\bin\elm-test:178:24)
    at C:\Users\drathier\AppData\Roaming\npm\node_modules\elm-test\bin\elm-test:303:33
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by mgold** [comment]
`cd test && npm test` should work a little better.

**Comment by drathier** [comment]
Sorry, I am not able to reproduce this, should've made an sscce right away. I'm guessing this was a corrupted npm installation on my machine, I don't remember being able to reproduce it on osx, and I stopped seeing it a few days later, probably when I reinstalled npm. 

I'd closevote this issue until we see it again.

**Comment by rtfeldman** [comment]
Sounds good, thanks! ❤️
