### ISSUE TITLE
Watch mode tracks changes only in the tests directory

### ISSUE THREAD

**Issue by megapctr** [elm-community/elm-test#104]
When I run `elm-test --watch` and change a source file so that a test would fail, the tests don't get executed. Then, if I save a test file without modifying it, the tests will execute and report a failure.

**Comment by robertjlooby** [comment]
This should probably be an issue on https://github.com/rtfeldman/node-test-runner, not here.

**Comment by mgold** [comment]
Seems to be resolved in the other repo.
