### ISSUE TITLE
Add Fuzz.errorProneString?

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/elm-test#107]
Just found this [repository of "naughty" (read: error-prone) strings](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt) which has this stated purpose:

> The Big List of Naughty Strings is an evolving list of strings which have a high probability of causing issues when used as user-input data.

Since one of the great things about fuzzers is helping you find edge cases, I can see it being useful to provide easy access to these right out the box.

I don't think it makes sense to lump these in with `Fuzz.string`, since not all strings are potentially coming from arbitrary user input, but adding a `Fuzz.errorProneString` seems like it could be useful. In particular I know that certain Unicode characters can lead to surprising results in conjunction with `String.length`.

Has anyone wanted this, or something like it?

**Comment by mgold** [comment]
Good find! However, if I want to test a particular function with these strings, I'd probably want to feel every one of them into a particular parameter of a function known to deal with untrusted input, instead of a randomized subset. The counterclaim is that a fuzzer would be useful to combine with other fuzzers.

**Comment by mgold** [comment]
There's also `blns.json` which appears to be a valid Elm expression, so it wouldn't be too hard for someone to keep these in another file and import them. Might be worth a third-party lib though.

**Comment by zkessin** [comment]
I would think this would be a useful fuzzer to have

**Comment by rtfeldman** [comment]
I'm on board with the third-party library idea. If it ends up seeing enough use in third-party libraries, we can always bring it in!
