### ISSUE TITLE
Function fuzzer?

### ISSUE THREAD

**Issue by joneshf** [elm-community/elm-test#109]
I noticed that there's no `Fuzzer (a -> b)` in `Fuzz`. I can't see how to create this fuzzer external to this library, though maybe I'm missing something. I couldn't find any information in a search. Has there been any discussion of adding this?

There are at least a couple different reasons for wanting this:

1. When defining a new data type, I often write functions like `map : (a -> b) -> Foo a -> Foo b`. I'd like to ensure that `map` is well behaved. That is, I should be able to fuzz that composition "works":
    ```elm
    composition : Fuzzer (a -> b) -> Fuzzer (b -> c) -> Fuzzer (Foo a) -> Test
    composition fuzzerAB fuzzerBC fuzzerFoo =
      Test.fuzz
        fuzzerAB
        fuzzerBC
        fuzzerFoo
        "composition works: map bc (map ab foo) == map (bc << ab) foo"
        (\ab bc foo ->
          Expect.equal (Foo.map bc (Foo.map ab foo)) (Foo.map (bc << ab) foo)
        )
    ```
    It's not always a trivial thing to show that without fuzzing. And it's not only `map` that I want to ensure it well behaved. There are many functions we write that have succinct equations but depend on arbitrary functions.
1. I have at least a few different data types that contain functions. A trivial example of such a data type is:
    ```elm
    type Predicate a
      = Predicate (a -> Bool)
    ```
    In order to fuzz anything about `Predicate a`, I need a function fuzzer. This example might seem simple, but I have more complex data types that are not so simple I'd still like to fuzz.

Both of these are things I'm running into right now. Though they have been simplified, they are real things.  Thoughts?

**Comment by mgold** [comment]
1. For defining `map`, I typically will just use integers. Using type variables gives you some guarantees at the type level. One of these is that there does not exist a function `f : a -> b` for all types `a` and `b`. That is, you can't turn an arbitrary type into a different arbitrary type. So randomly generating such functions is rather tricky!

2. Similarly, the only ways to generate a `Predicate a` for all `a` are `Predicate (\_ -> True)` and `Predicate (\_ -> False)`. If you have a concrete type, you can write some functions and pick between them, or from a family of functions. For example, you can select an integer between 0 and 31 (or 53) at random, and then see if an integer has a 1 at that bit. (Rightshift n, and with 1, equate with 1.)

So, I conclude that fuzzing on arbitrary types is impossible, and the next best options are possible using existing tools.

**Comment by joneshf** [comment]
Sorry for being unclear. Yeah, you'll definitely need to concretize something in the fuzzer :smile:. But the `composition` example is valid code (at least, once `Foo a` is defined and `Test.fuzz` is replaced with `Test.fuzz3` :blush:). I just can't use it in a meaningful way because I have to choose specific functions rather than letting the functions be fuzzed.

What I'm missing is how to fuzz arbitrary functions once you've decided on the types. Like if I know that I want `Fuzzer (Int -> List Bool)` as a fuzzer. I can of course say `Fuzz.constant (\_ -> [])` and get a `Fuzzer (Int -> List Bool)`. But, I want arbitrary functions of type `Int -> List Bool` to be generated. How can I make that?

**Comment by mgold** [comment]
I still think that what you want isn't possible in the type system. *You* may know what the concrete types are but my code doesn't! How would such a fuzzer be called?

The only thing I can think of that might possibly work is: run `toString` on the input, hash that string into a random seed, and use that to generate a value from a supplied fuzzer. Except you want many of these functions, so you'd use some randomness in the closure of the function to perturb the seed. This is **extremely** hacky and I'd rather not do it, but you'd wind up with something like `f : Fuzzer a -> Fuzzer (b -> a)`. There wouldn't be a way to constrain `b` since `toString` takes an unconstrained input.

**Comment by joneshf** [comment]
§3.3 of [prior art][prior-art] says we need something like:

```elm
type alias Cofuzzer a b = a -> Fuzzer b -> Fuzzer b

promote : (a -> Fuzz b) -> Fuzz (a -> b)

function : Cofuzzer a b -> Fuzzer b -> Fuzzer (a -> b)
function cofuzzer fuzzer =
  promote (\a -> cofuzzer a fuzzer)
```

Problem is, I can define neither `promote` nor any `Cofuzzer a b` functions. At least, not any `Cofuzzer a b` functions that aren't trivial.

[prior-art]: http://www.cs.tufts.edu/~nr/cs257/archive/john-hughes/quick.pdf

**Comment by rtfeldman** [comment]
This isn't a complete solution, but it fills in some of the missing pieces.

Say we set aside shrinking for now and add this to `Fuzz.Internal`:

```elm
promote : (a -> Fuzzer b) -> Fuzzer (a -> b)
promote toFuzzer =
    let
        fromBool : Bool -> Fuzz (a -> b)
        fromBool single =
            if single then
                Gen (toGenerator toFuzzer)
            else
                Debug.crash "TODO handle shrinking"
    in
        Fuzzer fromBool
```

That gets us closer, and we can implement `toGenerator : (a -> Fuzzer b) -> Generator (a -> b)` in terms of this:

```elm
promoteGenerator : (a -> Generator b) -> Generator (a -> b)
```

Looking at [how QuickCheck implements this](https://github.com/nick8325/quickcheck/blob/master/Test/QuickCheck/Gen/Unsafe.hs), the key seems to be `delay`, which can be implemented in Elm like so:

```elm
delay : Generator (Generator a -> a)
delay =
    Random.independentSeed
        |> Random.map genFromSeed


genFromSeed : Random.Seed -> Generator a -> a
genFromSeed seed gen =
    Random.step gen seed
        |> Tuple.first
```

Here's how QuickCheck uses `delay` to implement `promote`:

```haskell
promote :: Monad m => m (Gen a) -> Gen (m a)
promote m = do
  eval <- delay
  return (liftM eval m)
```

It's past midnight and I don't know Haskell well enough to desugar this offhand, but maybe someone who does can take it from here. 😄

**Comment by rtfeldman** [comment]
Okay, got it! `delay` wasn't strictly necessary after all.

Here is an implementation of `Fuzz.function` that type-checks. (It doesn't support shrinking, though, which is `Debug.crash "TODO"` right now - I'm not sure how that ought to work.)

```elm
function : (a -> Fuzzer b -> Fuzzer b) -> Fuzzer b -> Fuzzer (a -> b)
function cofuzzer fuzzer =
    promote (\val -> cofuzzer val fuzzer)


promote : (a -> Fuzzer b) -> Fuzzer (a -> b)
promote toFuzzer =
    let
        fromBool : Bool -> Fuzz (a -> b)
        fromBool single =
            if single then
                Gen (toGenerator toFuzzer)
            else
                Debug.crash "TODO handle shrinking"
    in
        Fuzzer fromBool


{-| CAUTION: uses unpackGenVal!
-}
toGenerator : (a -> Fuzzer b) -> Generator (a -> b)
toGenerator toFuzzer =
    Random.independentSeed
        |> Random.andThen
            (\seed ->
                Random.constant
                    (\a ->
                        seed
                            |> Random.step (unpackGenVal (toFuzzer a))
                            |> Tuple.first
                    )
            )
```

**Comment by rtfeldman** [comment]
Opened a WIP PR: https://github.com/elm-community/elm-test/pull/110

**Comment by mgold** [comment]
Can I see a use case of this function used to test something not guaranteed by types?

**Comment by joneshf** [comment]
Sure! Here's a random smattering of examples. Is there something in particular you'd like to see?

* There's the first example I listed: https://github.com/elm-community/elm-test/issues/109#issue-201570126
  * The types cannot guarantee that `Foo.map f (Foo.map g foo) = Foo.map (f << g) foo`, depending on what `Foo a` is. This applies to most of the common data types with the shape of `f a` for some `f` that provides a `map : (a -> b) -> f a -> f b`. Whether that `f` is `List`, `Maybe`, `Result String`, `Cmd`, `Html`, or whatever.
* There's `Test.filter`: https://github.com/elm-community/elm-test/blob/4b5e71c14479fbef471f2730f3c84c88e071d681/src/Test.elm#L39-L57
  * The types don't guarantee that you remove any expectations in the given `Test`. For all the types know, it's adding more tests! But you should be able to check that you get back loosely fewer expectations after `filter`ing.
  * The types don't guarantee that filter is idempotent. No matter how many times I `filter`, I should get the same result.
* There's `Test.test`: https://github.com/elm-community/elm-test/blob/4b5e71c14479fbef471f2730f3c84c88e071d681/src/Test.elm#L85-L99
  * The types don't guarantee that the function given is used at all to make the `Test` that is returned. But you could check that.
  * The types also don't guarantee how many expectations are made in the test.
* There's `Expect.all`: https://github.com/elm-community/elm-test/blob/4b5e71c14479fbef471f2730f3c84c88e071d681/src/Expect.elm#L581-L612
  * The types don't guarantee that the list is used at all. But you could check that whatever `Expectation` you got was the result of one of the functions in the list.

Parametricity does get you quite a bit. I fully support that! But it only goes so far. And it completely falls apart if the function isn't polymorphic.

**Comment by joneshf** [comment]
> Here is an implementation of Fuzz.function that type-checks. (It doesn't support shrinking, though, which is Debug.crash "TODO" right now - I'm not sure how that ought to work.)

That's awesome! Sorry, I haven't really looked into how that might work either :no_mouth:.

**Comment by rtfeldman** [comment]
I'm curious what the code for one of those tests would look like (using this `Fuzz.function`) - if anyone wants to make a PR to add an example to https://github.com/elm-community/elm-test/pull/110 - that would be sweet!

**Comment by rtfeldman** [comment]
Something to consider if we ever revisit this:

<img width="677" alt="screen shot 2017-04-20 at 5 44 45 pm" src="https://cloud.githubusercontent.com/assets/1094080/25258002/1160c56e-25f1-11e7-9fba-70a537be03f0.png">

**Comment by jwoudenberg** [comment]
I really like the idea of this.

With regards to the debugging problem, if we pass `promote` an extra string naming the `toFuzzer` function we should be able to provide a stringified version of the fuzzed function:

```elm
-- Suppose we have the following fuzzer generating 'multiplying functions'
multiplications : Fuzzer (Int -> Int)
multiplications = promote "multiplications" (\n -> Fuzz.int |> Fuzz.map ((*) n))


-- Function as printed in test failure (use it to debug your test from the repl!):
--     Fuzz.Debug.fn multiplications 1234567


-- Fuzz.Debug
fn : (a -> Fuzzer b) -> Seed -> a -> b
fn toFuzzer seed a =
     Test.Runner.fuzz (toFuzzer a)
         |> (\gen -> Random.step gen seed)
         |> Tuple.first
```

The only problem I see is stringifying the seed in such a way that we can recreate the original seed from it. Do you know if that's possible @mgold?

In addition, every fuzzer would need to take a `toString` property in addition to taking a generator and a shrinker (this could default to `Basics.toString` for almost all cases).

With regards to shrinking: it seems we'll somehow need to leverage the existing shrinking behaviour from the fuzzer being promoted. I'll give it some thought.

**Comment by rtavenner** [comment]
One thing that nobody has brought up yet: The `promote` function would also be useful for defining fuzzers for lazy infinite data structures.

```
import Lazy exposing (Lazy)
import Fuzz exposing (Fuzzer)


promote : (a -> Fuzzer b) -> Fuzzer (a -> b)
promote =
    Debug.crash "This is a proposed function."

lazy : (() -> Fuzzer a) -> Fuzzer (Lazy b)
lazy = Fuzz.map Lazy.lazy << promote


-- An infinite stream of values.
type alias Stream a =
    Lazy (StreamView a)

type StreamView a
    = Stream a (Stream a)

stream : Fuzzer a -> Fuzzer (Stream a)
stream f =
    lazy (\() -> 
        Fuzz.map2 Stream 
            f 
            (stream f)))

```

I don't know if this is useful, but it's something to think about.
