### ISSUE TITLE
Use casperJs to run the tests

### ISSUE THREAD

**Issue by amitaibu** [elm-community/elm-test#11]
Like this devs won't need to mock any `browser` in node.

Here's the [Travis](https://github.com/Gizra/generator-elmlang-example/blob/master/.travis.yml#L14) config and the simple [test](https://github.com/Gizra/generator-elmlang-example/blob/master/runTests.js#L9-L11) it executes.

Would a PR to the README with some explanation be the right approach?

**Comment by eeue56** [comment]
If people want to use CasperJS with this, then that's up to them. I don't think this is the right approach however, and there is work being done on a new version of Elm-test that will make this approach obsolete
