### ISSUE TITLE
Either Fuzz.list or Fuzz.frequencyOrCrash doesn't shrink properly

### ISSUE THREAD

**Issue by Janiczek** [elm-community/elm-test#112]
**EDIT: after some more analysis, the problem is with lists not shrinking properly and I have a fix.**

I'm getting weird behaviour for [shrinking of `Fuzz.frequencyOrCrash`](https://github.com/elm-community/elm-test/blob/3.1.0/src/Fuzz.elm#L777-L781).

I'm using it to test TEA `update` function with fuzzed list of `Msg` and it doesn't seem to shrink properly - more specifically, **it shows redundant failures instead of just the minimal one.**

When I used an `Fuzz.intRange` ("enum") implementation instead of `Fuzz.frequencyOrCrash`, the issue disappeared, so I have a reason for believing there is a bug in `Fuzz.frequencyOrCrash`.

## Expected output:
```
✗ After taking product, it shouldn't be vended

Given ([AddMoney,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended
```

## Actual output:
```
✗ After taking product, it shouldn't be vended

Given ([AddMoney,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended


Given ([AddMoney,TakeProduct,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended


Given ([AddMoney,TakeProduct,TakeProduct,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended


Given ([Buy,AddMoney,TakeProduct,TakeProduct,TakeProduct,Buy,Buy],TakeProduct)

    Vended
    ╷
    │ Expect.notEqual
    ╵
    Vended
```

## [SSCCE >>here<<](https://gist.github.com/Janiczek/04d994667057ff7bd194387db3f36d78)

**Comment by rtfeldman** [comment]
I wonder if this is `Fuzz.frequencyOrCrash` or just `Fuzz.list`, since the list is the only part of the tuple that seems to be shrinking improperly.

@Janiczek would you mind trying to reduce this even further, to just use `Fuzz.list`, and see if it still reproduces the shrinking issue?

**Comment by Janiczek** [comment]
I have tried to use `Fuzz.list` and `Fuzz.intRange` instead of `Fuzz.list` and `Fuzz.frequencyOrCrash` and the issue disappeared.

**Comment by Janiczek** [comment]
Interesting twist: I have tried experimenting with different integer ranges (see below) and **made the issue appear even with `Fuzz.list` and `Fuzz.intRange`.**

(Maybe that's for another issue?)

## Before (no issue):
```elm
        -1 -> {- AddMoney    -} if model == NoMoney then EnoughMoney else model
        0 ->  {- Buy         -} if model == EnoughMoney then Vended else model
        1 ->  {- TakeProduct -} model
```

## Step-in-between (no issue):
```elm
        1 -> {- AddMoney    -} if model == NoMoney then EnoughMoney else model
        2 -> {- Buy         -} if model == EnoughMoney then Vended else model
        3 -> {- TakeProduct -} model
```

## After (issue present):
```elm
        3 -> {- AddMoney    -} if model == NoMoney then EnoughMoney else model
        2 -> {- Buy         -} if model == EnoughMoney then Vended else model
        1 -> {- TakeProduct -} model
```

I know that **ints shrink towards zero** but probably can't connect the dots together right now...

**Comment by Janiczek** [comment]
OK, so after sprinkling `Debug.log` into a few places in `elm-test`, it seems that **`[1,2,3]` doesn't ever shrink into `[1,3]`**. It would seem like a good thing to do for me.

Right now it only slides windows over the original list, ie. shrinks into sublists of consecutive values of some length.

I'd add removing one element from the list (every position) into the list-shrinking methods. @mgold do you know why it isn't there already? Was the resulting rose tree too big, too time-consuming?

**Comment by Janiczek** [comment]
With removing the elements the issue disappears. `[1,2,3]` gets shortened to `[1,3]` and now I have only one failure.

I'm not sure about the efficiency of the implementation though:
* without removing of the elements the test takes around 100ms
* with it: anywhere from 190ms to 873ms

Is this a good idea?

```elm
listShrinkHelp listOfTrees =
    let
        -- ...snip...
        removed =
            List.range 0 (n - 1)
                |> Lazy.List.fromList
                |> Lazy.List.map (\index -> removeOne index listOfTrees)
                |> Lazy.List.map listShrinkHelp

        removeOne index list =
            List.append
                (List.take index list)
                (List.drop (index + 1) list)
    in
        shrunkenVals
            |> Lazy.List.append shortened
            |> Lazy.List.append removed
            |> Lazy.List.cons (RoseTree.singleton [])
            |> Rose root
```

**Comment by Janiczek** [comment]
For list of n elements, this shrinking strategy adds around `f(n) = n + n * f(n-1)` shrinking possibilities but in reality there are just `n^2 - 1` unique ones...

That is:
```length of list: 1 2  3  4   5    6     7 ...
taken:          1 4 15 64 325 1956 13699 ...
unique:         1 3  7 15  63  127   255 ...
```

The he amount of time taken is 2x to 10x worse... maybe some sharing/memoization of 'already done' shrinks would help? ie. don't do shrinking of [1,2,3] wrt. a currently running test if you have already done it?

This could greatly benefit other shrinking functions too. What do you think?

**Comment by rtfeldman** [comment]
> Maybe some sharing/memoization of 'already done' shrinks would help? ie. don't do shrinking of [1,2,3] wrt. a currently running test if you have already done it?

This makes sense to me, but @mgold is the expert. 😄

**Comment by Janiczek** [comment]
I'm experimenting with that, but I'm not currently getting what I'd like to see :D

![selection_076](https://cloud.githubusercontent.com/assets/149425/22239064/deb94fe8-e214-11e6-9485-49121ad73c0e.png)

**Comment by mgold** [comment]
Sorry I haven't been able to look at this, I appreciate your experimentation! I probably still won't have time to dig in in the next few days either.
