### ISSUE TITLE
Proposal: Having two tests / suite with the same title should fail the tests

### ISSUE THREAD

**Issue by jfmengels** [elm-community/elm-test#115]
I'm proposing a breaking change, that would aim users to have a better test suite (or at least better documented in a way):
- having two tests in a test suite share the same title should fail the tests
- having two test suites inside another test suite share the same title should fail the tests

The reasoning is kind of the same as for #95. If I have two tests with the same title, I have probably copy-pasted a test without updating the title. Enforcing different titles for every test should help have more descriptive tests. For reference, In JS land, popular testing frameworks like Mocha and AVA have ESLint plugins with rules that detect identical titles for tests and test suites.

Let me know what you think :)

**Comment by rtfeldman** [comment]
I love this idea! @mgold what do you think?

**Comment by mgold** [comment]
Seems a little bit finicky to implement but we have precedent for failing obviously wrong test cases. OP seems to suggest checking siblings and parent-children only, which seems right to me. There's probably a legitimate use for sharing names among grandchildren.

**Comment by zkessin** [comment]
i would say not across cousins, but otherwise makes sense

**Comment by rtfeldman** [comment]
Yeah, I'm thinking this could be as simple as maintaining a `Set (ListString)` of each "fully qualified" (in the sense of this being a list of ancestor descriptions for a particular test) and then erroring out if we try to add an entry to the set that's already present.

**Comment by mgold** [comment]
Or making a set from a list and checking the lengths of each, although that wouldn't give you a good error message.
