### ISSUE TITLE
Idea: `frequency` fails early instead of returning `Result` or crashing

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/elm-test#116]
It bothers me that [`Fuzz.frequency`](http://package.elm-lang.org/packages/elm-community/elm-test/3.1.0/Fuzz#frequency) has to either crash or return `Result`, due to the possibility of passing it invalid weights.

What if instead, we introduced a new type constructor to `Fuzzer` called `InvalidFuzzer String`, and the semantics were:

1. If `fuzz` receives any `InvalidFuzzer` instances, it does not run the test and instead fails with "sorry, I got an invalid fuzzer that had this problem: ________." and then printed the `String` error message inside `InvalidFuzzer (for example "got an invalid frequency: ______")
2. If you `andThen` any fuzzer with an `InvalidFuzzer`, you end up with the `InvalidFuzzer`

This way, we could get rid of `frequencyOrCrash` and just have `frequency` return a `Fuzzer` instead of a `Result String Fuzzer`. This would be a simpler API, and it would still let you find out in a nice way if you specified an invalid fuzzer.

**Comment by mgold** [comment]
Didn't we have this discussion in #56?

Granted, that might have been before [this representation](https://github.com/elm-community/elm-test/blob/master/src/Fuzz/Internal.elm#L32-L38). I suppose it's worth looking in to if we're doing a major release.

**Comment by rtfeldman** [comment]
Yep! Although [as this comment in that discussion noted](https://github.com/elm-community/elm-test/issues/56#issuecomment-244827694):

> I do think `frequency` should change if we either change internals to have `Result` _or_ if we change runners to support "fail on exception."

**Comment by rtfeldman** [comment]
A separate question: does it make more sense to have an invalid fuzzer result in:

* A failed test
* The entire test run erroring out before running tests, saying something like "you have an invalid fuzzer; you need to fix it before I can run tests!"

I can see arguments either way. Thoughts?

**Comment by rtfeldman** [comment]
Main argument for "one failed test": it doesn't block you, meaning you can fix other failing tests and then deal with the invalid fuzzer. (Is that useful? I don't know.)

**Comment by rtfeldman** [comment]
Main argument for "don't run any tests" - this is essentially the same as a compiler error, except there's no way to make this be *literally* a compiler error (without making the API super painful) because it needs to verify that the weights sum to more than zero.

Blocking anything from running is as close to a compiler error as we can get without it actually being a compiler error.

**Comment by mgold** [comment]
Causing a test failure is probably fine.

I have an implementation of this on the `invalid-fuzzer` branch but it's based on (and blocked by) #117.

I didn't read the old issue to closely before implementing, so instead of generating results, we have a result of a generator (basically). This keeps the invalidation separate from the randomness, which would otherwise be a big headache.

Although I didn't think about it until just now, this makes `Fuzz.filter` possible, if we accept a little heuristic. Generate n (about 10) values with a throwaway seed. If they all fail the predicate, that's invalid. Otherwise do the filtering.

**Comment by rtfeldman** [comment]
I'd rather stick with the flake-proof `Fuzz.conditional` over `Fuzz.filter` to be honest.

**Comment by mgold** [comment]
That's fine, and this PR doesn't implement that. I'd like to move on 117 so I can merge this one.
