### ISSUE TITLE
'Native' undefined when importing a module that uses native modules

### ISSUE THREAD

**Issue by oakesja** [elm-community/elm-test#12]
When importing a class that uses native modules, I receive the following error:

``` 
Elm.Native = Elm.Native || {};
                ^
TypeError: Cannot read property 'Native' of undefined
```

**Comment by eeue56** [comment]
This is no longer valid native code in 0.17.

**Comment by hickscorp** [comment]
Is there a place that documents the native API of Elm, and possibly a list of things that are expected to be deprecated?

**Comment by rtfeldman** [comment]
@hickscorp see https://groups.google.com/forum/m/#!topic/elm-dev/bAHD_8PbgKE

**Comment by mgold** [comment]
To loosely quote Evan from a recent Elm Town podcast, "why should I have a document to say that something isn't a thing"? Essentially, stay out of native/kernel code. And in the case of this repo, do as we say, not as we do :P
