### ISSUE TITLE
Recursive fuzzer crashes 

### ISSUE THREAD

**Issue by folkertdev** [elm-community/elm-test#124]
Creating a recursive fuzzer (for instance for tree data structures, like ASTs) gives the following javascript error

```
result:9688 Uncaught TypeError: Cannot read property '_0' of undefined
```

tweaking laziness doesn't seem to help (also the issue doesn't seem to be stack size, but something else). 

an SSSCE 

```elm
module Main exposing (..)

import Test exposing (..)
import Expect
import Fuzz exposing (list, int, tuple, string)
import Test.Runner.Html


type Expr
    = Parens Expr
    | Empty


expr =
    Fuzz.frequencyOrCrash
        [ ( 1, (\_ -> Fuzz.map Parens expr) () )
        , ( 1, Fuzz.constant Empty )
        ]


exprToString ex =
    case ex of
        Parens expr ->
            "(" ++ exprToString expr ++ ")"

        Empty ->
            ""


all : Test
all =
    describe "evaluating the `expr` fuzzer results in a js error"
        [ fuzz (expr) "" <|
            \expr ->
                exprToString expr |> String.toList |> Expect.equal []
        ]


main =
    Test.Runner.Html.run all
``` 

run it [on runelm.io](https://runelm.io/c/2k8)

**Comment by mgold** [comment]
This is almost certainly an Elm runtime error that occurs because of the way `expr` is defined recursively. There's an easy workaround:

```elm
expr : Fuzz.Fuzzer Expr
expr =
    Fuzz.intRange 0 100
        |> Fuzz.map exprFromInt


exprFromInt : Int -> Expr
exprFromInt i =
    if i > 0 then
        Parens (exprFromInt (i - 1))
    else
        Empty
```

Does this help?

**Comment by folkertdev** [comment]
In the slack channel I see people having similar issues with lazy decoders, so it is indeed probably a general elm issue. 

Your suggestion works well for two constructors in my original post, because the frequency is implicit. 
How would you update the fuzzer when the AST has more constructors (e.g. square brackets), in particular 
when I want one to be more common then the other.

**Comment by mgold** [comment]
Could you make your type not recursive and just have a list? `[Parens, Brackets, Brackets, CurlyBraces]`? You could use frequency for each tag and pass that to `Fuzz.list`.

**Comment by folkertdev** [comment]
maybe it's a good idea to take a step back 

the original goal is to generate valid syntax trees to test a parser: a generated syntax tree converted to a string should parse back to the same syntax tree. 

My particular use case is quite simple and indeed could use something like you describe, but I was inspired to write this fuzzer by a question in the testing slack channel by @stil4m who tried to create a fuzzer for the type 

```elm
type ExprPart
    = Literal String
    | Operator ExprPart String ExprPart
    | Parenthesized ExprPart
```
[full code](https://gist.github.com/folkertdev/93bd8964087801be17a9a42eb125701b)

For any sort of tree-like grammar, producing a list of tokens is not so helpful, because we cannot know that the whole list forms a syntactically valid expression. Some general solution for fuzzing tree-like structures would be much nicer

**Comment by mgold** [comment]
Hmm. First of all, when you move from a list to a tree, your odds of infinitely expanding the value go from "theoretically possible" to "pretty darn likely". So  you will need to enforce a constant depth limit.

What about something like
```elm
fuzzExprPart i =
  if i <= 0 then
    Fuzz.map Literal Fuzz.string
  else
    Fuzz.frequency ... -- recursive calls are given (i-1)

**Comment by folkertdev** [comment]
That fixes it, apparently.
 
here is [a running example with ellie ](https://ellie-app.com/t2477yKgPja1/0)

**Comment by stil4m** [comment]
Nice!

**Comment by mgold** [comment]
That doesn't fix it because you pass literal `5` to recursive calls. If you open dev console you will find that the same JS error occurs (at least on Chrome/Mac). This error causes the test to fail.

[Here](https://ellie-app.com/tgTPnB6x45a1/0) is a minimally-invasive fork that fixes the issue by passing the depth limit (minus one) to `operator` and `parenthesized`.

Randomly generating a tree without a depth bound is infinite recursion. Solving the halting problem is out of scope for elm-test.
