### ISSUE TITLE
License: copyright elm-community?

### ISSUE THREAD

**Issue by drathier** [elm-community/elm-test#129]
It seems a bit weird to me that this project has this copyright notice:

`Copyright (c) 2016-2017 Richard Feldman and Max Goldstein`

since the contributor list has grown a bit. How about `Elm-test contributors` or `Elm community` instead?

**Comment by eeue56** [comment]
Agreed.

**Comment by rtfeldman** [comment]
Fine by me! Happy to accept a PR for this.
