### ISSUE TITLE
Fuzzer.andThen hangs

### ISSUE THREAD

**Issue by jwoudenberg** [elm-community/elm-test#132]
Hey there. I just ran into an issue using `Fuzzer.andThen`. After whittling the testcase down a bit, the smallest reproducible variant looks a bit like the one below. The problem seems to be with `andThen`.

```elm
module Experiment exposing (spec)

import Fuzz
import Expect
import Test exposing (Test, fuzz)


fuzzer : Fuzz.Fuzzer Int
fuzzer =
    Fuzz.int
        |> Fuzz.andThen (always Fuzz.int)


spec : Test
spec =
    fuzz fuzzer "This will hang" <| \foo -> Expect.fail "Test failed"
```

This might be related to #105 #62 but I'm not a hundred percent sure.

cc @Stoeffel

**Comment by mgold** [comment]
I can't reproduce by adding this code to `tests/FuzzerTests.elm`, right beneath the other `andThen` test:

```elm
        , fuzz
            (int |> andThen (always int))
            "This will hang"
          <|
            \_ -> Expect.pass
```

Can you tell me more about your setup? Is the fact that this minimal reproduction (which is great btw) doesn't have a `main`? Do you still get the error with `Fuzz.map abs` or something?

**Comment by rtfeldman** [comment]
@mgold Does it need to `fail` instead of `pass`?

Maybe shrinking is what hangs...🤔

**Comment by jwoudenberg** [comment]
@mgold Yeah, as @rtfeldman mentioned, the `fail` is essential. With it, the shrinker starts producing an endless list of values.

**Comment by stoeffel** [comment]
@jwoudenberg we also saw that the produced values where not really shrinking.

**Comment by mgold** [comment]
> the `fail` is essential

Oh. Ooooooh. Huh. Yup.

Here's the existing test of `andThen` modified to fail:

```elm
, fuzz (andThen (\i -> intRange 0 (2 ^ i)) (intRange 1 8))
        "Fuzz.andThen"
        (Expect.atMost 2) -- passes with 256
```

This shrinks correctly. So this is likely not a regression. I suspect you may have found some kind of pathological situation in which the shrink path is either huge or loops.

Adding a `Debug.log` to the function will print `-877591785` (even after multiple trials, huh?) and then hang. Strange.

**Comment by mgold** [comment]
BTW: If you're not careful, these hanging test will leave `elm-test` processes running that noticeably slow down your machine. They must be `kill -9`-ed.

**Comment by stoeffel** [comment]
> They must be kill -9-ed.

Thanks for the heads up, I think @jwoudenberg always killed elm-test.

>  which the shrink path is either huge or loops.

If I recall it looked like it was looping.

**Comment by jwoudenberg** [comment]
Yeah, what Stoeffel said. And thanks for the quick response! I managed to work around by not using andThen, but figure it's still an interesting bug.

**Comment by jwoudenberg** [comment]
I think I now understand why this hangs. Consider a failed fuzzer as a combination of some original value plus a set of shrunken values. In the case of an int, that latter set can potentially be quite large if the original int was large.

Now consider `andThen`, which needs to combine two fuzzers (the original one and the one returned from the `andThen`-function. For the shrinking behaviour this is basically a flatmap: a new set containing all the possible combinations of both input fuzzers, the size of which is the square of the int size. Trying them all takes a while.

**Comment by mgold** [comment]
Yeah, that sounds about right.

**Comment by jwoudenberg** [comment]
I cannot reproduce this problem anymore. I think before #167 the entire RoseTree was being resolved in each shrink step, which might have been the reason for the hanging behaviour, so my previous diagnosis might have been false.

Closing this because it's fixed.

**Comment by mgold** [comment]
That's great news!
