### ISSUE TITLE
Fuzzers for `a` and `comparable`

### ISSUE THREAD

**Issue by drathier** [elm-community/elm-test#139]
It would be nice with fuzzers for "any type" and "any comparable", preferably in a such a way that no two fuzzers generate the same `a` in the same test run.

**Comment by mgold** [comment]
I understand the feeling of "why do I test `List a` functions with a list of Ints?", but this isn't possible in Elm's type system.

**Comment by zkessin** [comment]
not to mention that in general if you see something takes a type of "a" it means that the actual value of a does not matter as the function can not access it

**Comment by drathier** [comment]
We can at least show that you are intending to test `a` rather than `Int`. A simple version could define a type and not expose its constructor. Exposing `a`, `b`, `c`, `d`, `e` should be enough. For `comparable` we can use something like `(String, Int, Float, Int)` and hope that nobody uses that type already, once again to show intent, even if that type leaks out. A more advanced version could generate some source code with random types on each run, but I think the simple version would be enough for most use-cases.

**Comment by mgold** [comment]
A 4-tuple of comparable types won't play well with shrinking. And this is not accepted by the compiler:

```elm
foo : comparable
foo = (2, 3.4, "five")
```

You can never get an actual value of type `a` or type `comparable`. You can only write functions that will work with any such type, or empty contains of arbitrarily typed items (`[] : List a`, `Cmd.none : Cmd a`).

**Comment by drathier** [comment]
Ah, I once again forgot about shrinking. As for the actual types, I know we cannot instantiate a type variable without using a concrete type, but the written tests could mention the type variables, rather than concrete types that fit those variables. Even if we define `comparable=int` for the fuzzers, I still think it would be useful for conveying meaning; you intended to test a `comparable`, so 

```
fuzz comparable "set insertion" <| 
  \key -> Set.insert key ...
``` 
is more meaningfull than 
```
fuzz int "set insertion" <| 
  \key -> Set.insert key ...
``` 
even if both fuzzers generate ints.

**Comment by mgold** [comment]
Seems like someone could just write `comparable = Fuzz.int` in their test code and use that. Let's see if anyone does.
