### ISSUE TITLE
Expect.within weird tolerance?

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#146]
Hey @drathier, why does this test pass?

```elm
test "floating point equality with tolerance" <|
  \() ->
    3.14 |> Expect.within 0.001 pi
```

`pi - 0.001` is still greater than 3.14, so I'd expect this test to fail. Am I missing something?

**Comment by drathier** [comment]
Probably because of relative tolerance: `pi - 0.001*pi < 3.14 < pi + 0.001*pi`, or `3.138 < 3.14 < 3.145`. I haven't traced your test yet.

I'm becoming more and more convinced that abstracting away floating point numbers into a single comparator was a mistake, and that we should expose some composite api, like `withinAbsolute` and `withinRelative`, or `within {absoluteTolerance=0.001, relativeTolerance=0}`. Since `within` isn't published yet, we should really look into this before 4.0.0. 

I'm swamped with work right now, I'll look into `within` after the 22nd.

**Comment by mgold** [comment]
Okay, thanks for the update and the time projection.

I agree completely that I don't want to ship this expectation if we have any doubts about it. What do you and @rtfeldman think about pulling it out and into 4.1.0, assuming Richard can have the other work done soon enough to make it worth it?

**Comment by rtfeldman** [comment]
Yeah, that makes sense to me. `Expect.within` isn't critical for `4.0.0`, so I'd just as soon take it out and re-add the API we actually want in `4.1.0`.

@drathier any objections to that plan?

**Comment by drathier** [comment]
Either way works fine by me. It would be nice to ship it in 4.0.0 if it's done by then; it seems like it could be, given that there are still 4 other things to do. Otherwise releasing it in 4.1.0 works too.

**Comment by drathier** [comment]
Here are some cases we need to consider:

1. should NaN compare equal? (should fuzzers generate NaN?)
2. should near-zero be considered equal? (how near?)
3. should tolerance account for denormalized floats?
4. should tolerance account for near-infinity? (how near?)

This looks like the perfect use of an options map, but that's a bit verbose. 

Is it completely crazy to do something like this?
```
options =
  { absoluteTolerance = 0
  , relativeTolerance = 0
  , nanEquality = False
  , infinity = 1.0 / 0.0
  , zero = 2 ^ -1074
  , denormalizedTolerance = True
  }
```
along with
```
3.14 |> Expect.within {Expect.options | relativeTolerance = 0.000001 } pi
```

The default `Expect.options` would then be equal to `==`, and use scaling for denormalized floats if a tolerance is specified. Infinity is the number that is large enough to be considered equal to infinity, defaulting to `Infinity`. Zero is the number that is small enough to be considered equal to zero.

It's still an open question if absolute and relative tolerance should be OR'd or AND'ed together. I think they should be OR'd, but that might lead to the confusion that made @mgold open this issue.

**Comment by mgold** [comment]
Removing release blocker keyword since this was backed out.

**Comment by drathier** [comment]
I'd like your thoughts on the api design here. I'm still having trouble deciding.

**Comment by mgold** [comment]
> Also, does the float fuzzer generate `NaN` and `Infinity`?

No.

Honestly I don't know enough about the details of floating point to suggest a flexible API. But I think the no-nonsense (naive?) version is, `Expect.within a tol b` passes when `a - tol < b` and `a + tol > b` (or perhaps nonstrict inequality).

**Comment by drathier** [comment]
Your version is absolute tolerance. We also want relative tolerance. Those two are good enough for most use-cases. 

Would `3.14 |> Expect.within {absolute=0.01, relative=0.03} pi` work?
`3.14 |> Expect.within 0.01 0.03 pi`?
`3.14 |> Expect.within {absoluteTolerance=0.01, relativeTolerance=0.03} pi`?

Adding `Expect.any` and having `Expect.withinAbsolute` and `Expect.withinRelative`?

Using the options map I mentioned before?

**Comment by mgold** [comment]
Hmm, what about:

```elm
type FloatingPointTolerance = Absolute Float | Relative Float | AbsoluteAndRelative Float Float

Expect.within : Float -> FloatingPointTolerance -> Float -> Expectation
```

**Comment by mgold** [comment]
Fixed in the new PR.
