### ISSUE TITLE
Cannot create new assertions

### ISSUE THREAD

**Issue by niksilver** [elm-community/elm-test#15]
I'd like to create new assertions - e.g. assertHaveTheSameElements, or assertEqualTo4DecimalPlaces, etc - not in this module, but just for my own code. However, I cannot see how to do that. I think it would be possible if there was a function like this:

```elm
-- Asserts that the given Assertion failed
assertFailed : Assertion -> Assertion
```

Or (better) maybe create a function which can simply determine whether an Assertion is a pass or fail, e.g.

```elm
hasPassed : Assertion -> Bool
```

I am willing to have a go at `assertFailed` or `hasPassed` and make a pull request if you're happy with this idea.

**Comment by rtfeldman** [comment]
@niksilver I believe when we merge the project-fuzzball changes in here, the `Expect` module (which will replace `Assert`) should [cover this use case](http://package.elm-lang.org/packages/project-fuzzball/test/5.0.4/Expect).

Does it sound like that would do the trick?

**Comment by niksilver** [comment]
@rtfeldman Yes, thanks, that would do it. For the record I could create my own `Expectation` like this:

```elm
expectToBeClose : Int -> Int -> Expectation
expectToBeClose a b =
    if (abs (a-b) <= 1) then
        Expect.pass
    else
        Expect.fail (toString a ++ " is not close to " ++ toString b)

-- And it's used like this...

testSimple : Test
testSimple =
    describe "simple test"

    [ test "Some test" <|
      \() -> expectToBeClose 1 3
    ]
```

Look forward to fuzzball's inclusion.
