### ISSUE TITLE
elm-test init fails

### ISSUE THREAD

**Issue by mbuscemi** [elm-community/elm-test#152]
Running `elm-test init` yields `Error reading elm-package.json: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/elm-test/templates/tests/elm-package.json'`.

Installed using `npm install -g elm-test@beta`.

**Comment by mgold** [comment]
Thanks for the report! Maybe this belongs on the [runner's repo](https://github.com/rtfeldman/node-test-runner)?

**Comment by mbuscemi** [comment]
Thank you. I've opened a similar bug there: https://github.com/rtfeldman/node-test-runner/issues/126
