### ISSUE TITLE
Expect.member feature request

### ISSUE THREAD

**Issue by andys8** [elm-community/elm-test#155]
I'd like to propose a feature request for an `Expect.member` assertion to test if a collection (list, array, set) contains a specific item. 

Elm has [`member : a -> List a -> Bool`](http://package.elm-lang.org/packages/elm-lang/core/latest/List#member), but I think it could be part of the `elm-test` api. The main advantage is the user could receive useful error messages if the assertion fails which is not the case when using `Expect.equal`.

There is a package called [`elm-test-extra`](http://package.elm-lang.org/packages/ktonon/elm-test-extra/1.4.0/)  that provides the [`member`](http://package.elm-lang.org/packages/ktonon/elm-test-extra/1.4.0/Expect-Extra#member) matcher. But in my opinion I'd prefer to have it as part of `elm-test` because of two reasons:
1. It's a common matcher that should be part of the library
2. There is a long term risk if depending on many small packages instead

#### Other testing libraries as comparison
* Chai has [`to.include(item)`](http://chaijs.com/api/bdd/#method_include)
* Jasmine has [`toContain(item)`](https://jasmine.github.io/2.6/introduction)
* Jest has [`toContain(item)`](https://facebook.github.io/jest/docs/expect.html#tocontainitem) (forked jasmine)
* Elm-test-extra has [`member`](http://package.elm-lang.org/packages/ktonon/elm-test-extra/1.4.0/Expect-Extra#member)

**Comment by drathier** [comment]
Having the same function check for membership in lists, arrays, sets and/or other containers won't type-check, but just checking lists works fine.

**Comment by drathier** [comment]
Do we want to implement this?
ping @mgold @rtfeldman

**Comment by mgold** [comment]
I don't see an incredibly compelling reason to add it, especially if it's in the -extra package.

**Comment by drathier** [comment]
It doesn't look like this is getting added right now, so I'll close this for now.
