### ISSUE TITLE
Code question: Why are the Fuzzer RoseTree's opt-in?

### ISSUE THREAD

**Issue by jwoudenberg** [elm-community/elm-test#162]
I've been diving into the fuzzer code a bit to see if I can help out with some of the open fuzzer issues here. I was hoping someone might be able to answer one thing that has been puzzling me, which is why the Fuzzer's RoseTree's are opt-in, considering they're lazy. 

To be clear, I get that we don't want to do the work of generating shrunken values for the case that the test passes, but can't we rely on the laziness of the RoseTree's children to achieve that? I believe it would simplify code quite a bit if we could express the fuzzer like this:

```elm
type alias Fuzzer a = Valid (Generator (RoseTree a))
type Valid a = Valid a | Invalid String
```

I'm wondering if there's any theoretical obstacles to this. Practically speaking, I'm giving this a try and will report back with what I find. On that note: if anyone has some benchmarks for elm-test lying around I'd be interested to get a copy. If not, I'll create a PR containing some if there's an interest.

**Comment by mgold** [comment]
The opt-in business was a performance optimization, only, and if you can demonstrate that it doesn't make things faster we can get rid of it. Benchmarks would be a great contribution on this front.

The theory is that, even though the Rosetrees are lazy you still have to build up a lot of closures, and these have a cost even if they are not executed. Since we know they are unneeded if the test passes, we opt-in to generating them.

**Comment by jwoudenberg** [comment]
Thanks! I'm going to try look at those benchmarks and see if I can measure the effect of the optimisation.

**Comment by jwoudenberg** [comment]
It's a real shame we can't write the generator and the shrinker as two interpreters working on a dumb data structure:

```elm
type Fuzzer b
    = Custom (Generator b) (Shrinker b)
    | Map (a -> b) (Fuzzer a)
    | AndThen (a -> Fuzzer b) (Fuzzer a)

custom : Generator a -> Shrinker a -> Fuzzer a
custom = Custom

map : (a -> b) -> Fuzzer a -> Fuzzer b
map = Map

andThen : (a -> Fuzzer b) -> Fuzzer a -> Fuzzer b
andThen = AndThen

toGenerator : Fuzzer a -> Generator a
toGenerator fuzzer =
  case fuzzer of
    Custom generator _ -> generator
    Map mapFn prev -> toGenerator prev |> Random.map mapFn
    AndThen andThenFn prev -> toGenerator prev |> Random.andThen andThenFn

shrunkenGenerator : Fuzzer a -> Generator (LazyList a)
shrunkenGenerator =
-- Non trivial implementation which would still be easier than what we have now.
```

**Comment by mgold** [comment]
> The following fails because `a` is not exposed on the Fuzzer type.

I believe this is called an [existential type](https://wiki.haskell.org/Existential_type) and is unlikely to be added to Elm in the immediate future.

**Comment by rtfeldman** [comment]
I think that's actually a GADT, which I think is likely to be added sometime in the (not immediate, granted) future.

**Comment by jwoudenberg** [comment]
Seems you're both right: https://stackoverflow.com/questions/25103835/gadt-vs-existentially-quantified-types-forall

> GADTs came along later than existentials, and they generalise them. I'm not aware of any drawbacks and would always use GADT syntax in new code as it's much clearer.

**Comment by jwoudenberg** [comment]
Closing this since I have my answer. Thanks!
