### ISSUE TITLE
running elm-test fails with compilation error

### ISSUE THREAD

**Issue by mkovacs** [elm-community/elm-test#174]
```
$ elm-test
Compilation failed for elm-stuff/generated-code/elm-community/elm-test/src/Main<HASH>.elm
```

I'm on Windows 10, installed `elm-test` via npm.

**Comment by MattCheely** [comment]
I am having a similar issue with npm installed elm-test on Linux. Some possibly useful output:

```
▶ elm-test --verbose
Running elm-make /home/mcheely/projects/elm-time/tests/Main.elm /home/mcheely/projects/elm-time/tests/TestDate.elm /home/mcheely/projects/elm-time/tests/TestDateTime.elm /home/mcheely/projects/elm-time/tests/TestZonedDateTime.elm --output /dev/null --yes
Running elm-make /home/mcheely/projects/elm-time/elm-stuff/generated-code/elm-community/elm-test/src/Main33ef0594a82bf39f1071368966778ec6.elm --output /home/mcheely/projects/elm-time/elm-stuff/generated-code/elm-community/elm-test/elmTestOutput.js --yes
Compilation failed for /home/mcheely/projects/elm-time/elm-stuff/generated-code/elm-community/elm-test/src/Main33ef0594a82bf39f1071368966778ec6.elm
```
Running the failing elm-make command manually:

```
▶ elm-make /home/mcheely/projects/elm-time/elm-stuff/generated-code/elm-community/elm-test/src/Main33ef0594a82bf39f1071368966778ec6.elm --output /home/mcheely/projects/elm-time/elm-stuff/generated-code/elm-community/elm-test/elmTestOutput.js --yes
I cannot find module 'Main'.

Module 'Test.Generated.Main33ef0594a82bf39f1071368966778ec6' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

**Comment by prikhi** [comment]
If you're running the latest `elm-test`, make sure you've removed `tests/Main.elm`, removed `node-test-runner` from `tests/elm-package.json` and bump the major version of `elm-test` in `tests/elm-package.json`.

**Comment by MattCheely** [comment]
@prikhi That's fixed it, Thanks!  The root of the issue was that `elm-community/elm-time` is still set up for elm-test 3.x, and I wasn't expecting to have to check version compatibility between the CLI and the project dependencies. It might be worth adding a note to the README about making that check when running `elm-test` for existing projects so that it doesn't catch other folks out. 

Thanks again for the help!

**Comment by mkovacs** [comment]
@prikhi That solved the issue, thank you!

**Comment by ZzAntares** [comment]
Hi @MattCheely @prikhi I'm having the exact same issue, but I can't fix it by following your instructions, if there's a dependency conflicting how do I know which one is causing the problem?

These are my dependencies:

```json
        "NoRedInk/elm-decode-pipeline": "3.0.0 <= v < 4.0.0",
        "elm-community/elm-test": "4.1.1 <= v < 5.0.0",
        "elm-community/html-test-runner": "1.0.3 <= v < 2.0.0",
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0"
```

Thanks in advance for any help you can give :grinning:
