### ISSUE TITLE
Compilation failed for elm-stuff/generated-code/elm-community/elm-test/src/Mainf0d769d3faab65e5c3d6b7dbe1470495.elm

### ISSUE THREAD

**Issue by happysalada** [elm-community/elm-test#178]
I am working on a public repository that can be found [here](https://github.com/happysalada/git-involved.elm)

I ran `elm-test init`
Then replaced in the example file, with the examples found on the readme of elm-test.
When I run `elm-test` here is the output I have from the console
```
› elm-test
Compilation failed for /Users/Raphael/Documents/Projects/Umbrela/Elm/git-involved.elm/elm-stuff/generated-code/elm-community/elm-test/src/Mainf0d769d3faab65e5c3d6b7dbe1470495.elm
```

I'm sure I'm doing something wrong somewhere, but I just can't figure out what.

Here are additional information
```
› which elm
/usr/local/bin/elm

› which elm-test
/usr/local/bin/elm-test
```

Let me know if you need any more informations

**Comment by mgold** [comment]
Related to #176?

**Comment by happysalada** [comment]
I deleted the elm-stuff directory and all of its content in the main folder, and re-running elm-test worked for me
