### ISSUE TITLE
Debug.log instead of debug.crash?

### ISSUE THREAD

**Issue by proProbe** [elm-community/elm-test#18]
In `ElmTest.Runner.Console` on `line 33` there is Debug.crash. Running failing elm-tests gives an ambiguous error that confuses the user on where the error actually is at. Suggest that it changes to Debug.log instead.

**Comment by eeue56** [comment]
Debug.crash is used so that you get a non-zero exit code. Debug.log will not give this. A version with improved text output is in the works. For now, Debug.crash is just fine.
