### ISSUE TITLE
Expose an API for stepping fuzzers or using them with Tasks

### ISSUE THREAD

**Issue by avh4** [elm-community/elm-test#185]
I want to use fuzz tests to test external systems, which will require running a sequence of Tasks to produce the output value that I want to validate.  Using tasks won't fit with using an elm-test runner, but I'd like to use `Fuzz` to help me generate and shrink examples that I can execute in a normal Elm program.

To do that, either `Fuzz` would need to expose a way to step through the shrinking results for a generated value, or it would need to provide a way to work with Tasks.

Possible API for stepping:

```elm
Fuzz.start : Fuzzer a -> Random.Seed -> (a, Shrink a, Random.Seed)
Fuzz.step : Shrink a -> Maybe (a, Shrink a)
```

Possible API for working with Tasks:

```elm
Fuzz.Task.fuzz : Fuzzer (Task Never a) -> (a -> Expectation) -> Task Never Expectation
```

**Comment by jwoudenberg** [comment]
Cool! I think the first option is already supported by the `Test.Runner.fuzz` and `Test.Runner.shrink` functions.

**Comment by avh4** [comment]
Ah, great!  I wasn't expecting anything useful in `Test.Runner` so I didn't look there.

Closing for now.  (The Tasks fuzzer could be implemented on top of that, and could be in a separate package.)
