### ISSUE TITLE
Remove dependency on elm-lang/html and elm-lang/virtual-dom?

### ISSUE THREAD

**Issue by mikegehard** [elm-community/elm-test#19]
I have an elm program that doesn't have any UI element yet when I `elm package install elm-community/elm-test` I am required to install elm-lang/html and elm-lang/virtual-dom.

Does elm-test need to have a dependency on those two packages?

**Comment by mikegehard** [comment]
Ah I see what it is now...you can generate HTML to run the suite in the browser instead of using Node.

Wondering if it is worth separating these two parts so that someone who only wants Node doesn't have extra dependencies in their elm-package.json?

**Comment by eeue56** [comment]
Right now, the only way to create a valid program is via Html/Virtual-dom. It's not possible to remove the dependency and cheap this as pure Elm.

**Comment by mikegehard** [comment]
Thanks for the explanation and all of your hard work.
