### ISSUE TITLE
Fuzz.string should generate whitespace strings

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#198]
Inspired by [this comment](https://github.com/elm-community/elm-test/issues/193#issuecomment-316040569).

I'm thinking 5-10% of the time, produce 1-5 characters drawn from space, tab, and newline.

**Comment by rtfeldman** [comment]
I like it! 👍

**Comment by drathier** [comment]
I think we should follow the unicode character properties for this, except doing another grouping (e.g. all "whitespace" in the same group). Pick a random class, then a random character from that class. https://en.wikipedia.org/wiki/Unicode_character_property We can define a few groups, leaning towards more ascii characters than rest of unicode, and use `frequency` to genereate this. 

I'd be happy to take on this issue. I need to refresh my unicode knowledge anyway.

**Comment by drathier** [comment]
I feel like `string` generating only ascii letters is a very US-centric way to do things. Most functions that use fuzzed strings should work just fine with all of unicode. I'll leave the name for now, but I feel like we should change the name and possibly split it up into ascii-letters and unicode later.

**Comment by mgold** [comment]
@drathier You should open another issue, and tag it "release blocker" if you're proposing a breaking change.
