### ISSUE TITLE
module name conflicts (Util)

### ISSUE THREAD

**Issue by dustinfarris** [elm-community/elm-test#210]
I have a `Util.elm` which seems to conflict with elm-test's module of the same name.

This is the output I get:

```
-- NAMING ERROR --------------------------------------------- ./../elm/Store.elm

Module `Util` does not expose `=>`

38| import Util exposing ((=>))
```

If I rename my module to `Utilities` the error goes away.

**Comment by jwoudenberg** [comment]
Hey there! On what basis do you believe it's elm-test's `Util` that you have the conflict with? The module does exist, but it is not exposed from this library (https://github.com/elm-community/elm-test/blob/master/elm-package.json), so it shouldn't cause conflicts with module's of that name outside the library.

Could it be that your conflicting `Util` module comes from a different library? Or perhaps you have a `Util.elm` both in your test directory and your source directory?

**Comment by dustinfarris** [comment]
Hi @jwoudenberg thanks for the reply.  I'm basing this on not having any conflicts until I installed and ran elm-test.  :-)

**Comment by jwoudenberg** [comment]
Ok, fair enough :-).

Just for my understanding, did you add elm-test as a dependency to your root project, or did you create a separate directory containing your tests and installed elm-test in there? In the latter case, could it be that your test modules and source modules both contain a `Util.elm` module?

**Comment by dustinfarris** [comment]
This output might be helpful (elm-package.json files and tree):

https://gist.github.com/dustinfarris/28f138f4b64b522147d881c027a746bc

I do not have any other module called Util.

Another observation, I can add

```
import Util exposing (rangeLengthList)
```

and there are no errors with reference to that.  (that is an export from elm-test's rangeLengthList)

However this only happens if I happen to have Util.elm as well.  If I rename Util.elm to Utilities.elm, and then try the above import, I get 

```
I cannot find module 'Util'
```

Also, elm-make does not reflect these errors, it continues to give the feedback you would expect in any of these scenarios.  It's only when I have a Util.elm and run elm-test that I am seeing this.

**Comment by jwoudenberg** [comment]
I've tried to reproduce your situation here but haven't managed to reproduce your error: https://github.com/jwoudenberg/debug-elm-test-issue-210

It seems to find the local `Util` module fine, both when running `elm-make` and when running `elm-test`. Also when I try exposing `rangeLengthList` I get the expected error that Util doesn't expose that function for either command.

Am I doing something different in that repo than you? Does it compile / test correctly for you in that repo?

**Comment by dustinfarris** [comment]
I adjusted the repo to reflect my scenario and it still does not reproduce what I am seeing in my private project.

**Comment by jwoudenberg** [comment]
Interesting. Perhaps we can work from the other end, removing code / packages from your private project to work towards the simpler scenario in the repo I shared? The point at which it stops failing might tell us something useful.

**Comment by drathier** [comment]
I just hit this as well, when initializing elm-test in a project that already had a module named Util. Elm-make works fine in the project root, but when run from elm-test, which imports my source from a `../` directory, it finds the Util in elm-test itself, rather than the one in my project. A quickfix would be to prefix all elm-test modules with `ElmTest`, which is ... not ideal. I'm guessing this is a compiler bug.

**Comment by eeue56** [comment]
Colliding module names is not a bug. They should be prefixed.

**Comment by drathier** [comment]
@eeue56 `Util.elm` is not exported from elm-test, so you shouldn't be able to reference it from a module that just depends on elm-test.

SSCCE available at https://github.com/drathier/sscce-elm-test-util . Reporting as a compiler bug, since it only happens with an imported library (elm-test), which should be isolated.

**Comment by eeue56** [comment]
@drathier I don't follow your explanation

**Comment by eeue56** [comment]
@drathier I found the problem: 
```
"repository": "https://github.com/elm-community/elm-test.git"
```

Change that to anything that's not elm-community/elm-test and it will work. it should probably have a better default.

**Comment by mgold** [comment]
So in [this file](https://github.com/rtfeldman/node-test-runner/blob/master/templates/tests/elm-package.json) then?

`"https://github.com/user/project.git"` is probably fine, since it doesn't exist and also I think `elm package publish` gives an error if you try it.

**Comment by drathier** [comment]
Nice catch @eeue56! Opened a PR with @mgold's change and updated the compiler issue. All done from our side, and we have an easy fix for those affected. Good times!

**Comment by mgold** [comment]
@dustinfarris, please verify that changing the `repository` field in `tests/elm-package.json` resolves the issue.

**Comment by eeue56** [comment]
Closed due to the fact I'm certain this is fixed.
