### ISSUE TITLE
Utility expectations

### ISSUE THREAD

**Issue by andys8** [elm-community/elm-test#213]
I'd like to have utility expectations added to `elm-test`. Any chance they would be accepted or should they live in own libraries?  I want to know if there is interest in making the use of this library less verbose but potentially less concise.

I'm thinking about `isJust`, `isOk`, `isErr` (and not ignoring the error message like `err` does) for union types which are [imported by default](https://github.com/elm-lang/core#default-imports).

#### Example
Before
```elm
  val
  |> Expect.equal (Just Model.SomeValue)
```

After
```elm
  val
  |> Expect.isJust Model.SomeValue
```

**Comment by eeue56** [comment]
See this: https://github.com/elm-community/elm-test/issues/135

**Comment by andys8** [comment]
Thanks for the hint @eeue56 . Good to see more interest in the topic.
