### ISSUE TITLE
Make output coloring more legible

### ISSUE THREAD

**Issue by salutis** [elm-community/elm-test#218]
See the following `elm-test` output in Visual Studio Code's console:

<img width="211" alt="screen shot 2017-12-03 at 02 18 32" src="https://user-images.githubusercontent.com/1158274/33521370-687b0b84-d7d0-11e7-9b75-5c9e6e89c9d0.png">

I found it hard to read the `0` and `42`.

On a white background in macOS' Terminal, it's not much better:

<img width="235" alt="screen shot 2017-12-03 at 02 20 26" src="https://user-images.githubusercontent.com/1158274/33521373-8f651686-d7d0-11e7-9ef7-7328c1a7cb2d.png">

**Comment by drathier** [comment]
Pretty sure this is a request for the [node test runner](https://github.com/rtfeldman/node-test-runner) rather than for elm-test itself. 

@rtfeldman did we implement colors in the runners or in elm-test?

**Comment by rtfeldman** [comment]
Yeah, this is a runner issue.

@salutis can you reopen this on https://github.com/rtfeldman/node-test-runner/issues ?

**Comment by salutis** [comment]
@rtfeldman 

> @salutis can you reopen this [...]

Reopened as https://github.com/rtfeldman/node-test-runner/issues/229. Thanks!
