### ISSUE TITLE
elm-test --watch Parse Error

### ISSUE THREAD

**Issue by gogocurtis** [elm-community/elm-test#223]
Hi, for some reason "supervisor.js" is getting empty data and trying to parse it on line 121 

I think this happend when I upgraded to Node 8.6 LTS

I added this in supervisor so that when the data is empty it will not crash.
```
 if (!data) { return }
```

**Comment by drathier** [comment]
Supervisor.js is a part of the node test runner, rather than elm-test. It lives over at https://github.com/rtfeldman/node-test-runner/blob/master/lib/supervisor.js

Could you open an issue in that repo instead? :)

**Comment by zwilias** [comment]
@gogocurtis Also check you're on the latest version (0.18.12), I think [we fixed that](https://github.com/rtfeldman/node-test-runner/blob/0.18.12/lib/supervisor.js#L121-L125) :)

**Comment by drathier** [comment]
The best kind of bug report response; it's already fixed, and you can download the new version within the next minute 🌈

**Comment by gogocurtis** [comment]
Aww Thank you both! For pointing me to the right repo and highlighting the
fix!
