### ISSUE TITLE
runSuite output console output is very poor

### ISSUE THREAD

**Issue by lpil** [elm-community/elm-test#23]
Use of the `Debug.log` and `Debug.crash` functions result in a rather poor experience when running tests.

A passing suite has ` : ""` appended to the output for no obvious reason, and a failing suite comes with a large stacktrace and debugging information that is completely out of place.

**Comment by eeue56** [comment]
Please read the other closed issues about this.

**Comment by lpil** [comment]
This is not the same issue as reported in those.

I am not suggesting we do #18 , as that it doesn't fix the issue I highlighted with Debug.log, and it loses the exit status information, which is vital.

Use of the debug module either way is a bad solution. We need clean printing, and we need real control over exit statuses rather than using the ugly side effect of Debug.crash.

I believe the correct solution here would be to use ports as there we have more control over IO and the runtime.

**Comment by lpil** [comment]
Also there is absolutely no value in closing valid issues like this. Issues make a great TODO list that welcome other people to come and fix ugly warts like these.

**Comment by eeue56** [comment]
https://github.com/elm-community/elm-test/issues/18#issuecomment-222659202

**Comment by eeue56** [comment]
Most importantly: there is currently work underway by multiple community members to provide an alternate way to run tests, with prettier output and more features :)

**Comment by lpil** [comment]
Marvellous, good to hear. Thanks :)
