### ISSUE TITLE
Does Expect.true or false really need a description string, since test already has one?

### ISSUE THREAD

**Issue by HappMacDonald** [elm-community/elm-test#240]
Concrete example:
```
test "2 isEven"
  <|\_ ->
      MyBasics.isEven 2
      |>Expect.true "Pointless String"
```
I'd imagine most feeds into Expect.true/false will be simple function calls, because most core features that return Bool such as == or < already have bespoke Expect test functions that offer more verbosity.

Another way to look at it is that you'll never get the test string displayed in any instance where you're not already getting the Expect string displayed, unless there exists some more exotic kinds of expectation chaining than I've yet encountered.

rtfeldmen asked me to post an issue here so that other folk can weigh in on whether they find use for this descriptive text or not. So what do y'all think? :)

**Comment by drathier** [comment]
I did a little digging around across open source elm projects on github. People seem to do these things with `Expect.true`:
- `Expect.equal Expect.true Expect.true` (found one scary example)
- `Expect.equal True`
- `Expect.true "should be true"`
- people committing documentation.json which contains my elm-test-graph docs, which contains tests like `Expect.true "2 should be a member"`, where the string is differentiating different expectations. 
- people committing elm-stuff, which contains some test cases

I suggest dropping `Expect.true` and `Expect.false` and tell people to use `Expect.equal True` and `Expect.equal False` instead.

**Comment by HappMacDonald** [comment]
Yeah, I'm down for this. I'm not seeing any strict advantage to Expect.true given that it gains no visibility beyond what you'd get with Expect.equal. :)

**Comment by mgold** [comment]
I think the reasoning was to require a more descriptive string to explain the failure, but it hasn't panned out that way. For these apparently rare cases, `Expect.onFail` should suffice.

I wonder if the idea of having true and false matchers comes from JavaScript and Ruby testing, where you legitimately need truthy and falsy testing?

**Comment by rtfeldman** [comment]
> the reasoning was to require a more descriptive string to explain the failure, but it hasn't panned out that way.

Agreed on both counts!

> I suggest dropping `Expect.true` and `Expect.false` and tell people to use `Expect.equal True` and `Expect.equal False` instead.

I'm on board with this plan. 👍

**Comment by drathier** [comment]
Looks like we have achieved consensus. I've got a flight coming up, and I'd be happy to give it a go :)
