### ISSUE TITLE
(Cygwin) Piping buffered stdout with lots of Debug.log segfaults

### ISSUE THREAD

**Issue by HappMacDonald** [elm-community/elm-test#241]
By "Cygwin" I mean I have so far only tested this on Cygwin for Windows 10 64-bit via elm-test@0.18.13-beta2

By "buffered" I mean piping STDOUT to a process that fails to take input faster than elm-test emits output.

If I pipe into less, it segfaults at the end of the first page. (less has the first page of output but nothing farther)
If I tee, it segfaults after about 5kb of text.
If I just redirect to a file or obviously allow STDOUT to display on my terminal, no segfault occurs.

I do not know if this is related to Debug.log in particular, that's just the case where I noticed this happening. Maybe it also happens if you have a ton of ordinary test output as well, I have not yet tested this permutation.

**Comment by HappMacDonald** [comment]
[2018-07-19_elm-test_issue#241_example1.txt](https://github.com/elm-community/elm-test/files/2212533/2018-07-19_elm-test_issue.241_example1.txt)

**Comment by HappMacDonald** [comment]
OK, I've not got confirmation that a lot of output via non-Debug.log means (or at least via a single very large test description) does not appear to trigger this bug.

I've got a minimal test case here that will output plenty of Debug.log data to help replicate the issue. :)


[Q.elm](https://github.com/elm-community/elm-test/files/2212569/Q.elm.txt)

**Comment by rtfeldman** [comment]
Elm's `Debug.log` compiles to `console.log` in JS, which when run in Node.js results in data being sent to `stdout`.

This sounds like a Cygwin bug, and I don't think there's anything we can realistically do about it. 😅

**Comment by HappMacDonald** [comment]
Alright, yep in command prompt I can confirm that Q.elm won't segfault even while paging through dos's more. While I had not previously tested Cygwin more in particular, I just tested that one again and confirmed that it did.

Thus it is most likely just an interoperability issue with Cygwin, and I'll close. Thank you for checking Richard. :)
