### ISSUE TITLE
Call Stack Size exceeded with List-String-Fuzzer and Set

### ISSUE THREAD

**Issue by Y0hy0h** [elm-community/elm-test#246]
I have a case where a test fails because the call stack size was exceeded. I'm not really sure what is happening.

The test is:
```elm
module TestCallStack

import Expect
import Fuzz exposing (list, string)
import Set
import Test exposing (..)


suite : Test
suite =
    fuzz (list string) "stays inside call stack size limits" <|
        \strings ->
            Expect.equal (Set.toList <| Set.fromList strings) strings
```

The test output:
```
 > stays inside call stack size limits

    This test failed because it threw an exception: "RangeError: Maximum call stack size exceeded"
```

## Observations
This issue does not occur when `Set.toList` is not called (e. g. `Expect.equal (Set.fromList strings) (Set.fromList strings)`). I do not know how to test `Set.toList` to see if that is the problem.

Somehow natural, but reducing the number of fuzz tests (`elm-test --fuzz 10`) makes it less likely to encounter this issue.

I feel that this is related to #237, or that this might be an issue with the compiler outputting JS that causes this issue (StackOverflow turns up a [question that shows how to fix the problem](https://stackoverflow.com/a/22123896/3287963)). So I'm not sure if this repo is the right one to fix it.

**Comment by mgold** [comment]
@Y0hy0h Please upgrade to elm-explorations/test 1.1.0 and see if the issue continues.

**Comment by Y0hy0h** [comment]
That seems to have solved the problem! Thanks!

Just out of curiosity, what was the issue?

**Comment by mgold** [comment]
A mistranslation of code with custom operators to 0.19. Not complicated so much as subtle.

**Comment by Y0hy0h** [comment]
That sounds like one of those nasty bugs. Thanks for the explanation!
