### ISSUE TITLE
Convert from "fork" to regular repo?

### ISSUE THREAD

**Issue by lpil** [elm-community/elm-test#25]
It seems that this project is now sufficient different from the original dead project to be considered the canonical source of this codebase. Should we convert it to a regular repo, rather than a fork?

**Comment by rtfeldman** [comment]
This makes sense to me. Looks like the process for doing that is to contact GH support, which I'm happy to do.

Anyone else have thoughts on this? @mgold?

**Comment by mgold** [comment]
Yes, that makes sense to me. I'm a little surprised it isn't tracked as a fork of NRI's version but whatever.

**Comment by rtfeldman** [comment]
Done!

**Comment by lpil** [comment]
Hooray! :)
