### ISSUE TITLE
Watch Mode

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/elm-test#30]
Jacob on Slack had a cool idea, and I'm just gonna screencap it here:

![screen shot 2016-06-17 at 1 41 47 pm](https://cloud.githubusercontent.com/assets/1094080/16164025/48a30d5e-3491-11e6-99b2-0acbb6dd7549.png)

**Comment by lpil** [comment]
I've been wanting this for a while. Seems like it should belong in https://github.com/rtfeldman/node-test-runner, what do you think?

**Comment by rtfeldman** [comment]
Yup! Closing as duplicate of https://github.com/rtfeldman/node-test-runner/issues/51
