### ISSUE TITLE
404 link in the README to elm-community/elm-test-runner

### ISSUE THREAD

**Issue by jweir** [elm-community/elm-test#33]
The README points to the elm-test-runner, but is pointing to a 404.

Is it meant to point to ~~https://github.com/rtfeldman/node-test-runner~~ ?

EDIT: sorry that was obviously the wrong link, I am not sure where it is supposed to point.

**Comment by rtfeldman** [comment]
Thanks! Fixed in 0bab42323c1aa78ddac27bc3a225cb36d17f2f42
