### ISSUE TITLE
Wierd bug with intRange

### ISSUE THREAD

**Issue by Skinney** [elm-community/elm-test#39]
The following test:

```
         fuzz2 (intRange 1 32) (intRange 100 10000) "small slice end" <|
            \n size ->
                length (slice 0 (negate n) (initialize size identity))
                    |> Expect.equal (size - n)
```

Gives me the following error:

```
✗ Array
✗ Length
✗ small slice end

Given (0,100)

    0
    ╷
    │ Expect.equal
    ╵
    100
```

But how can it be given 0 when the range is between 1 and 31? Increasing the range to 2 and 31 fixes the problem.

The test is taken from Skinney/elm-array-exploration

**Comment by rtfeldman** [comment]
Hm, so the implementation of `intRange` is pretty simple:

```elm
intRange : Int -> Int -> Fuzzer Int
intRange min max =
    custom (Random.int min max)
        (Shrink.keepIf (\i -> i >= min && i <= max) Shrink.int)
```

Seems like there's a bug in a dependency... 🤔 

cc @mgold

**Comment by mgold** [comment]
Tracking in mgold/elm-random-pcg#9, though that doesn't rule out a bug in `shrink` as well.

**Comment by mgold** [comment]
@Skinney Please change `elm-package.json` to require `mgold/elm-random-pcg` version 3.0.1 rather than 3.0.0, and then verify that the bug has been resolved.

**Comment by Skinney** [comment]
Fixed :)
