### ISSUE TITLE
Elm Test runs exceptionally slowly on Travis CI

### ISSUE THREAD

**Issue by lpil** [elm-community/elm-test#42]
Here's my tests running from scratch on my laptop

```
louis $ rm -r tests/elm-stuff/build-artifacts/
louis $ time make test
./node_modules/.bin/elm-test
Success! Compiled 57 modules.                                       
Successfully generated /tmp/elm_test_116717-8806-iglcg.js

TEST RUN PASSED

Duration: 19 ms
Passed:   20
Failed:   0


real	0m5.469s
user	0m8.940s
sys	0m4.268s
```

It takes a few seconds to compile and run.

Here it is running on Travis CI -> https://travis-ci.org/hackathing/tea-and-pronouns/builds/152991988#L470

It takes 754 seconds to run. This is kinda painful.

Why is it so slow, and how might I resolve this?

**Comment by robertjlooby** [comment]
I wrote [a blog post](https://8thlight.com/blog/rob-looby/2016/04/07/caching-elm-builds-on-travis-ci.html) about this. Essentially, you can get a huge speedup by caching the build artifacts.

As with building locally, if you notice anything funky you should clear the cache before wasting too much time debugging as sometimes the compiler won't pick up some changes.

**Comment by rtfeldman** [comment]
@robertjlooby I was wondering about that - any particular reason you don't cache `elm-stuff/packages` too?

**Comment by robertjlooby** [comment]
You can. It only shaves off a few seconds though ([link](https://travis-ci.org/robertjlooby/elm-travis-cache-test/builds)). The big win comes from caching the build artifacts.

**Comment by rtfeldman** [comment]
Ah, gotcha. Is there any downside? One extra line of config for a few seconds seems worth it to me. :D

**Comment by rtfeldman** [comment]
Hm, I also wonder if caching the elm binaries could help...

**Comment by robertjlooby** [comment]
I don't think there's any downside to caching the packages or the elm binaries. There just isn't as much upside either.

Anything that is cached is just `tar`ed up and uploaded/downloaded to S3. So caching stuff that just gets downloaded doesn't make as much of a difference since it just increases the size of the cache. 

You save some time downloading stuff from npm/github but you spend some time downloading/uploading a bigger tarball.

**Comment by rtfeldman** [comment]
Oh cool! I did not know that's what Travis was doing behind the scenes there...thanks!

**Comment by lpil** [comment]
The local build was without any cache, see how rm the build artifacts on the first line.

It must be something else making it so much slower in CI. Any ideas?

**Comment by robertjlooby** [comment]
The thing that is slow on Travis CI is compiling the Elm code, not running the tests (or fetching the dependencies or anything else). I have no idea why compiling Elm code is slow on Travis, but there's nothing that could be done here on elm-test to speed it up. I'd suggest opening an issue on https://github.com/elm-lang/elm-compiler/ if you haven't already.

Also the `.travis.yml` file for this project does [cache the build artifacts](https://github.com/elm-community/elm-test/blob/master/.travis.yml#L5), so anyone using it as an example shouldn't run in to this same issue 😸

**Comment by zkessin** [comment]
It is also very slow on Circle-CI, at this point I have decided to just live with it

**Comment by zkessin** [comment]
Should we close this issue, it seems to not be an issue with elm-test

**Comment by robertjlooby** [comment]
I looks like someone finally dug in to it and it may be that the CI environments are misreporting the number of CPUs available https://github.com/elm-lang/elm-compiler/issues/1473. Now that Evan is aware it sounds like there may be an `elm-make` flag in the future.

**Comment by lpil** [comment]
Wonderful, thank you

**Comment by lpil** [comment]
I'd love to, but I doubt I'll have any time spare until after the 22nd I'm afraid.

**Comment by rtfeldman** [comment]
Based on how the Travis logs in OP show the elm-test output reporting 26 ms for excuting the tests themselves, it seems super likely that this is the compilation part.

I'm gonna close this and point people to https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-250637064

Thanks for reporting @lpil!
