### ISSUE TITLE
Multiple expectations per test / Expect.all

### ISSUE THREAD

**Issue by opsb** [elm-community/elm-test#49]
You often have want to run a common block of code and then perform multiple assertions. For normal tests you can achieve this by using a let ... in expression and having multiple tests, each with a single expectation. For fuzz tests however this isn't possible because the random values are only available in the test, you can't use them in the let ... expression e.g.  

```
addFeedTests store =
    let
        user =
            { id = 123, name = "Jim Bob", email = "jim@bob.com", idToken = "jwt" }

        ( store', cmd, maybeMsg ) =
            store
                |> Store.update defaultUpdateConfig (StoreApi.addFeed user "Feed one" feedUuid)

        { event, channel, payload } =
            Dict.values store'.phxSocket.pushes
                |> List.head
                |> unwrapMaybe
    in
        describe "addFeed"
            [ fuzz uuidFuzzer "message pushed to phoenix" <|
                \(feedUuid) ->
                    Expect.equal
                        ( event, channel, payload )
                        ( "addFeed", "feeds:lobby", Feed.encode feedUuid 123 "Feed one" )
            ]
```

Note the feedUuid is required for the Store.update but it isn't available until the fuzz test is reached. 

One option would be something like

```
expectAll : List Expectation -> Expectation
expectAll expectations =
    case expectations of
        [] ->
            Expect.pass

        x :: xs ->
            case Expect.getFailure x of
                Nothing ->
                    expectAll xs

                Just _ ->
                    x
```

(thanks to @gampleman for that snippet). Given a list of expectations this will return the first failure it hits or pass.

The only issue I see with this is when shrinking fuzz tests. If different expectations fail for different ranges of fuzz inputs then it won't be possible to converge correctly. I'm not sure how common an issue this would be but it's worth considering.

**Comment by mgold** [comment]
Could you
* create a fuzzer (using `map` etc) that produces the randomized values that you're interested in, rather than working with the relatively primitive UUID?
* use `Fuzz.tuple` to pass multiple randomized values to your test?

Then you could split out your three equality expectations into three different tests, without duplicating the setup code.

**Comment by mgold** [comment]
Hmm, here's a specific use case where this could be useful. This is testing a new fuzzer that produces strings whose length is in a given range.

```elm
Expect.all : List (a -> Expectation) -> a -> Expectation

fuzz (Fuzz.stringLengthRange 5 20) "stringLengthRange stays in range" <|
    \s ->  String.length s |> Expect.all [Expect.atLeast 5, Expect.atMost 20]
```

That said, maybe we need the less general `Expect.inRange 5 20` instead?

**Comment by zkessin** [comment]
I was wanting this the other day too

**Comment by mgold** [comment]
@zkessin Do you mean `Expect.all` or `Expect.inRange`? (Alternate name: `Expect.between`)

(This isn't JavaScript, I should have to guess what `this` refers to!)

**Comment by zkessin** [comment]
Expect.all

Though Expect.between sounds like it would also be useful , though with Expect.all you could build it

**Comment by opsb** [comment]
`Expect.batch` would be nice, then you could do 

```
inRange min max =
    Expect.batch [Expect.atLeast min, Expect.atMost max]
```

```
Expect.batch [inRange 5 20, Expect.someOtherCondition]
```

not sure how this would line up with the existing implementation for expectations though...

**Comment by mgold** [comment]
It would certainly be possible to take the first failing expectation, and possibly all of them.

I prefer `Expect.all` over `Expect.batch` because it communicates that you want all of the expectations to be true more clearly.

**Comment by zkessin** [comment]
I think Expect.all expresses the idea better, do we also want `Expect.some` which would pass if at least 1 expression passes?

**Comment by mgold** [comment]
It's certainly an obvious extension, but it makes tests less certain. "Well, it could be any one of these..."

**Comment by mgold** [comment]
Question: What should `Expect.all []` do? If you're passing a literal empty list, then that's definitely a bug in your test and should result in a failure. But if you're composing the list of expectations based on the input, then perhaps it should behave like `List.all` and pass. But if you're doing something that crazy, you open yourself up to not making an expectations of your input a lot of the time, which leads to false confidence in tests.

**Comment by opsb** [comment]
> I prefer Expect.all over Expect.batch because it communicates that you want all of the expectations to be true more clearly.

I was thinking `Expect.batch` would be nice describing hierarchies of expectations. Extracting higher level expectations like `Expect.inRange` then becomes very natural. I agree `Expect.all` is clearer though.

> I think Expect.all expresses the idea better, do we also want Expect.some which would pass if at least 1 expression passes?

Concrete example where you'd want this?

> What should Expect.all [] do?
In Qunit you specify the number of expectations for your test, perhaps something like 

```
Expect.all 3 
    [ Expect.condition1
    , Expect.condition2
    , Expect.condition3
    ]
```
or 
```
Expect.all3 
    Expect.condition1 
    Expect.condition2
    Expect.condition3
```
could work.

**Comment by zkessin** [comment]
I think Expect.some is one of those features that might be useful from time to time, but will probably cause more problems than it solves. 

As for Expect.all I can imagine something like this, a function that returns a string and I want to validate it vs several regexps. In general I would rather have 4 simple assertions vs 1 very complex one.

**Comment by zkessin** [comment]
I think Expect.all [] should probably be considered a bug, and should call Debug.crash or just fail with "No assertions provided"

**Comment by gampleman** [comment]
I (in my implementation above) treat it about the same as if you return `Expect.pass` in your test. i.e. if you want, you can make your test pointless in many ways.

The other option would be to check for this at the type level, i.e. make the function take `all : Expectation -> List Expectation -> Expectation`. That way it will always have at least on valid test in it. However I think that would make it just more annoying to use.

**Comment by zkessin** [comment]
I think either behaviour is ok, as long as it is well documented. 

I kind of defaulted to the idea that not having any assertions was a mistake and we should flag it.

**Comment by mgold** [comment]
> In Qunit you specify the number of expectations for your test

I think that's so it knows how many asynchronous operations it should wait for. `elm-test` is entirely synchronous.

> I kind of defaulted to the idea that not having any assertions was a mistake and we should flag it.

As did I. No reason to crash when it's easy to return a failing test.

Do people have a preference between these two type annotations? The first is more obvious and perhaps more flexible, but I think the second will be more useful in pipelines.

```elm
all : List (a -> Expectation) -> a -> Expectation
all : List Expectation -> Expectation
```

**Comment by zkessin** [comment]
@mgold I think Expect.all [] should return something like `Fail "Empty Expectation list"`

**Comment by gampleman** [comment]
Personally the first one would work better for me.

**Comment by opsb** [comment]
> I think that's so it knows how many asynchronous operations it should wait for. 

That's correct. The reason I suggest it really is that it List.map2/map3/map4 Decode.tuple2/tuple3/tuple4 etc. is such a common pattern in Elm. 

```
Expect.all3 
    Expect.assertion1 
    Expect.assertion2
    Expect.assertion3
```
vs
```
Expect.all
    [ Expect.assertion1
    , Expect.assertion2
    , Expect.assertion3
    ]
```
is a little clearer, particularly if you start including pipes to build your assertions.

**Comment by zkessin** [comment]
I like the list syntax better, Similar to Cmd.batch [ .. ]

**Comment by gampleman** [comment]
Also makes for cleaner diffs if you decide to add a test condition.

**Comment by zkessin** [comment]
some sort of chaining operator might be nice too

**Comment by mgold** [comment]
> The reason I suggest it really is that it List.map2/map3/map4 Decode.tuple2/tuple3/tuple4 etc. is such a common pattern in Elm.

These are used when you're mapping or decoding things of *different types*. When you have multiple things of the same type (either `Expectation` or `(a -> Expectation)`), use a list. This is how `Html` works and it's far cleaner to not have functions for N arguments than it is to avoid square brackets and commas.

> some sort of chaining operator might be nice too

How so? The list-of-functions form is meant to work with `|>` chains that elm-test uses fairly heavily. Supposing you didn't want to use `Expect.between` you could do `someInteger |> Expect.all [Expect.atLeast 0, Expect.atMost 4]`.

**Comment by opsb** [comment]
> These are used when you're mapping or decoding things of _different types_

Seems very obvious now :) thanks

**Comment by splodingsocks** [comment]
FWIW I'm a fan of Expect.all and throwing an error on `[]`
