### ISSUE TITLE
Should Fuzz.string generate long strings too?

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/elm-test#50]
@zkessin's PR https://github.com/elm-community/elm-test/pull/47 gave the example of encoder tests wanting longer strings as a reason to add `Fuzz.longString`.

This got me thinking - considering the whole point of fuzzing is to identify corner cases, really the desire to add a `longString` fuzzer is a bug report against the current `Fuzz.string`: we aren't generating the sort of values that are needed to cover common use cases.

Thinking about it further, it seems like rather than adding `Fuzz.longString` in the next release, we should just fix the current `Fuzz.string` to include long values some of the time.

Right now `Fuzz.string` generates strings between 0 and 10 characters in length. In contrast, `Fuzz.int` does this:

```
            Random.frequency
                [ ( 3, Random.int -50 50 )
                , ( 0.2, Random.constant 0 )
                , ( 1, Random.int 0 (Random.maxInt - Random.minInt) )
                , ( 1, Random.int (Random.minInt - Random.maxInt) 0 )
                ]
```

I think we should do something similar for strings: increase the chance of getting empty string, and include both some short-length strings as well as some really long ones (100+ chars).

Thoughts?

**Comment by rtfeldman** [comment]
cc @eeue56 @mgold

**Comment by mgold** [comment]
I would say yes. I'm pretty sure 0-10 characters comes from Hassan's original implementation and hasn't been rethought, until now. So based on `Fuzz.int` perhaps

```elm
    genLength =             
          Random.frequency
                [ ( 3, Random.int 1 10 )
                , ( 0.2, Random.constant 0 )
                , ( 1, Random.int 11 50 )
                , ( 1, Random.int 50 1000 )
                ]
```

I think this would give us a better mix of strings.

**Comment by zkessin** [comment]
In a conversation I had with John Hugues last year about this he said that longer is often better in that it increases the chance that some strange corner case will happen in the string if you are doing something where the content of the string matters

**Comment by mgold** [comment]
I agree with the comment - for 2.1.0, we should make longer (but still printable ASCII) strings, and remove `stringLengthRange`. Tagging this as release-blocker because I don't want to release that function.

**Comment by mgold** [comment]
Closing and removing release-blocker now that #54 has been merged.

**Comment by zkessin** [comment]
I still like the idea of being able to generate strings of a fixed length, as sometimes there are cases where that makes sense

**Comment by rtfeldman** [comment]
In that case I'd say the best way to go would be to open a separate issue
with its own motivating use case!
