### ISSUE TITLE
Should Fuzz.string generate Unicode strings?

### ISSUE THREAD

**Issue by zkessin** [elm-community/elm-test#51]
The current implementation generates 7 Bit Ascii strings, while of course may applications will want to use Unicode, we should have a generator for that

**Comment by rtfeldman** [comment]
I could see having the default answer be "yes" and adding a separate `Fuzz.asciiString` for when you know unicode strings will break your application (and are okay with that).

**Comment by mgold** [comment]
Honestly, I don't know. Unicode characters sound harder, or at least more computationally expensive, to shrink. But yes, printable ASCII is a fairly narrow defintion of a string. So, has anyone encountered a test that passed, but would have failed given Unicode strings? Or, similarly to how `Fuzz.float` does not generate `NaN`, are a lot of functions not written to handle unicode and that's okay?

**Comment by zkessin** [comment]
or leave Fuzz.string the way it is and add Fuzz.utf8String 

I would expect that there would be bugs that would only be found if you had a right to left text in your string (Hebrew, Arabic, Yiddish etc)

**Comment by rtfeldman** [comment]
Yeah, which is the biggest argument to me for changing the default. If
these are real bugs that could have nasty consequences if they went
undetected, shouldn't we try by default to surface them?

**Comment by zkessin** [comment]
I would agree with that, so having unicode be the default makes sense.

**Comment by mgold** [comment]
Is there a middle ground, like you want ç and å and ß and æ, but not right-to-left characters? Or maybe emoji?

Fuzzers should try to surface bugs, but I'm concerned that some people wouldn't consider "it fails for Arabic" to be a bug.

**Comment by zkessin** [comment]
I expect there should be, but I am not enough of an expert to say. For now lets leave it at ascii for 2.1.0 and do some research on how to do this for the future

**Comment by rtfeldman** [comment]
Agreed!

**Comment by zkessin** [comment]
I am also thinking that if we include hebrew/arabic etc it may confuse people because if the fault is involves two letters in an alphabet you don't know you may have trouble making sense of it.

if you had the string חה and it became  הח would you even notice if you were not a Hebrew speaker? (I am sure we could find similar examples in other charecter sets) 

That being said I think we should have fuzzers that can generate different alphabets, just not in the default string fuzzer

**Comment by mgold** [comment]
Perhaps the solution is to let people bring their own character fuzzers? Sounds awfully similar to `Fuzz.list charGen |> Fuzz.map (String.join "")` though.

**Comment by zkessin** [comment]
as some point I was planning to make word fuzzers, that would take the spell check dictionaries from different languages and use them generate lists of words, not sure when this will happen. So that way if you really want to know if your app will work for say German you can pick the correct fuzzer. 

It also has the advantage that random string generation has a very different entropy than actual text, which may matter for some tests

**Comment by rtfeldman** [comment]
I think the right resolution here is to say that the current `string` should remain the same, and if in the future someone needs Unicode fuzzers for a specific project, we can open a new issue at that time.
