### ISSUE TITLE
Should we add invalid Fuzzers / Fuzzers returning results?

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#56]
Currently (after #52 is merged), fuzzers are implemented as Bool -> Generator of either random values, or a rosetree of random values. This idea would add another layer of abstraction so that `Generator a` (a = value or rosetree of values) becomes `Generator (Result String a)`. If a fuzzer produces an `Err`, the test fails rather than crashing. Although this has a few different uses, I don't see any as a smoking gun:
- The safety of `frequency` with the interface of `frequencyOrCrash`
  - The list and weights are usually hard-coded and so `frequencyOrCrash` rarely crashes in practice
- `filter` can return invalid if n generated values are filtered out, rather than looping forever
  - The docs warn of this issue, and sensible people don't filter out nearly everything
- The many "impossible" calls to `Debug.crash" can be replaced
  - If they're not impossible, there's a bug and we want to know about it.
- Users can call `invalid` themselves if they want to
  - No concrete use case; can only be called in tests, not code under test

OTOH, implementing this feature would incur increased code complexity and a performance hit of unknown magnitude, even for passing tests. Furthermore, catching a crash should be the job of the runners, not `elm-test` itself.

So, I'm not convinced that this is a good idea, but I'm open to arguments to the contrary.

**Comment by mgold** [comment]
Also, this would likely be a major release, since we'd want to change the type signature of `frequency` and remove `frequencyOrCrash`.

**Comment by rtfeldman** [comment]
I'm open to the idea that "embrace `Debug.crash` for invalid test situations" might be the way to go, given that runners should gracefully handle exceptions anyway.

Incidentally, part of the reason I've shied away from `Debug.crash` on `frequency` is that currently the HTML runner can't gracefully handle them because it runs in Reactor straight from the `.elm` file, with no JS code involved. This means it can't handle exceptions.

That's not an explicit design goal, but I haven't thought through how it would look otherwise - maybe it would give you an `index.html` file that had a `<script>` tag you could edit to point to your compiled elm code? Certainly it'll need to run JS if it ever wants to run things in parallel and/or catch exceptions though, so I'm kind of assuming it won't be able to run in Reactor straight from the `.elm` file indefinitely.

**Comment by rtfeldman** [comment]
I do think `frequency` should change if we either change internals to have `Result` *or* if we change runners to support "fail on exception."

Once we're translating exceptions into test failures, `Result` won't even get you meaningfully nicer error messages anymore, so I don't think there'd be any point in having anything but (the function currently known as) `frequencyOrCrash` - which I'd rename to `frequency` in a MAJOR change.

**Comment by mgold** [comment]
Okay, so on the premise of designing for usecases and in response to feedback, and also because it would be a MAJOR change, I think we should let this sit for a bit. I think some of the new expectations that have been brought up by the community should be the focus of 2.2.0.

**Comment by rtfeldman** [comment]
I'm also comfortable saying this is blocked on getting exceptions translated into test failures. Until we know how that shakes out, we can't really know whether it'd be a good substitute for this.

**Comment by mgold** [comment]
You mean, by the runners? Oh right, in case the code under test crashes. Honestly that's a much more likely scenario than abusing `filter` or `frequencyOrCrash`.

**Comment by rtfeldman** [comment]
Right - exactly why we want it regardless!

**Comment by mgold** [comment]
I hadn't even thought of that!

**Comment by zkessin** [comment]
I like the idea that Debug.crash means a test fails, I have places in my code base where there is a Debug.crash with the note that the application state should never get there, but that I can't express that with types for some reason

**Comment by rtfeldman** [comment]
Linking to https://github.com/rtfeldman/node-test-runner/issues/69 for future reference

**Comment by rtfeldman** [comment]
Thinking about this more, I think it's best to close this in favor of https://github.com/rtfeldman/node-test-runner/issues/69 - I think both the HTML runner and the Node runner can support "exception means failed test" using some Native code, and that seems like the correct solution to work towards.
