### ISSUE TITLE
oneof fuzzer

### ISSUE THREAD

**Issue by zkessin** [elm-community/elm-test#58]
it would be useful to have a fuzzer one of

`oneof: List a -> Fuzzer a` to which you could provide a list of possible values and it would pick one. Esp useful for things like representing choosing an item from a list. 

Also useful in that you can provide it a list of words and create a string fuzzer that will generate strings that look more like actual text and less like random charecters. 

I will probably submit a PR for this in the next few days

**Comment by rtfeldman** [comment]
Thanks for the idea, but I don't think we should add this. I think a convenience wrapper around frequency for the case where you want all the frequencies to be 1.0 is not a common enough need to justify expanding the API.

It's hard to keep an API small and simple, but I think it's worth it!

**Comment by zkessin** [comment]
This is not so much about having all the frequencies have the same weight, as having the ability to have a fuzzer that chooses from a list of specific values, such as the days of the week. 

I found in Erlang code that this got used a lot
