### ISSUE TITLE
elm-package.json's elm-test dependency doesn't match tests/elm-package.json's elm-test dependency on elm-test init

### ISSUE THREAD

**Issue by willnwhite** [elm-community/elm-test#63]
After installing elm-test in a clean directory I've noticed that elm-package.json's elm-test dependency (2.1.0) doesn't match the tests/elm-package.json elm-test dependency (2.0.0) made by `elm-test init`. The instructions in the README are to copy all the dependencies from the former to the latter. If that is so, why does `elm-test init` make a mismatch for you?

**Comment by mgold** [comment]
The version in `tests/elm-package.json` is out of date purely out of oversight and I've sent a PR to fix it.

`elm-test` should not be present in the project root's `elm-package.json`. Otherwise it gets downloaded as a package dependency and sent to the browser!
