### ISSUE TITLE
Fuzzer for int values that are at least x

### ISSUE THREAD

**Issue by willnwhite** [elm-community/elm-test#64]
I'd like a fuzzer for int values that are at least x. In my case, I'm dividing a number (a donation amount) by a natural number of donees, so I'd like `intAtLeast 1`.

**Comment by robertjlooby** [comment]
could you use [Fuzz.intRange](http://package.elm-lang.org/packages/elm-community/elm-test/2.1.0/Fuzz#intRange) for this?

```
import Fuzz
import Random.Pcg as Random

fuzzer = Fuzz.intRange 1 Random.maxInt
```

**Comment by willnwhite** [comment]
Of course! Thanks. I'll PR the docs.
