### ISSUE TITLE
The README is out of date for version 0.17

### ISSUE THREAD

**Issue by tcoopman** [elm-community/elm-test#7]
still uses Graphics.Element, elementRunner,...
I don't have time for a PR at the moment. But I'll try to do it later this week if this isn't resolved by then.

**Comment by jaapz** [comment]
What should be used instead? I'm trying to get this to work, and I might make a PR when I figured it out, but not having correct documentation does makes stuff a bit harder to figure out :P

**Comment by klazuka** [comment]
This issue can be closed now that PR #21 was merged.
