### ISSUE TITLE
Add Fuzz.stringLengthRange

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#75]
It's come up on the Slack channel that sometimes you need a string of a specific length. We allow integer ranges so this wouldn't be a terrible thing to have.

See also #69, lists of given length, and #57, filtering fuzzers (e.g. to remove strings of undesired length). Filtering is likely to be ineffective in the case of wanting an exact length. Generating a list of known length can be coupled with `Fuzz.char` and `String.join` to implement this function.

**Comment by rtfeldman** [comment]
I'm going to close this and #69 for now. These both seem like the sort of thing someone will bring up if they run into a specific case where they would help out, and I think revisiting with that context will be more useful than leaving them open indefinitely waiting for that.
