### ISSUE TITLE
Should the README recommend symlinking elm-package.json?

### ISSUE THREAD

**Issue by lsimoneau** [elm-community/elm-test#79]
The README says:

>so make sure whenever you change your dependencies in your current elm-package.json, you make the same change to tests/elm-package.json.

This seems onerous, could we instead just symlink the tests one to the primary one? This could be suggested in the README, or it could even be the default behaviour of `elm-test init`.

**Comment by mgold** [comment]
It's a neat idea, but the two files should not be identical. First, elm-test itself should be a dependency of your tests but not your app. Second, this setup would make it way too easy to release your tests on elm-package.

**Comment by lsimoneau** [comment]
Was just discovering this myself. Apologies for the noise, I misread the instructions in the README and assumed it meant copy the file.
