### ISSUE TITLE
elm-test doesn't find compiler when installed through NPM

### ISSUE THREAD

**Issue by Anahkiasen** [elm-community/elm-test#80]
I've installed both `elm` and `elm-test` locally through NPM, however `elm-test` doesn't seem to be able to locate `elm-make` by default:

```bash
$ elm-test
Could not find Elm compiler "elm-make". Is it installed?

$ which elm-make
node_modules/.bin/elm-make

$ elm-make
Success! Compiled 0 modules.

$ elm-test --compiler $(realpath node_modules/.bin/elm-make)
Success! Compiled 81 modules.
Successfully generated /var/folders/g1/xqkylmwn4_x8mkyh5rf2cgkh0000gn/T/elm_test_1161013-51250-ldbbs7.gg24mo0f6r.js

elm-test
--------

Running 3 tests. To reproduce these results, run: elm-test --seed 738405972
```

As you can see, manually specifying the path does works, but could it be possible to make elm-test also look into `node_modules/.bin` by default?

**Comment by mgold** [comment]
This seems like a bug in the [test runner](https://github.com/rtfeldman/node-test-runner).

**Comment by Anahkiasen** [comment]
Oops sorry, will repost that here, I'm new to Elm
