### ISSUE TITLE
elm-test fails on 0.18

### ISSUE THREAD

**Issue by udnisap** [elm-community/elm-test#81]
I tried to setup elm-test on elm 0.18 and I get the following type error
```
==================================== ERRORS ====================================

-- TYPE MISMATCH ------------------------------------------------------ Main.elm

The definition of `main` does not match its type annotation.

 9| main : Program Value
10| main =
11|>    run emit Tests.all

The type annotation for `main` says it is a:

    Program Value

But the definition (shown above) is a:

    Test.Runner.Node.TestProgram

Detected errors in 1 module.
```

Are there any api changes as this was working fine in 0.17

**Comment by mgold** [comment]
You need to download the new version of [Main.elm](https://github.com/rtfeldman/node-test-runner/blob/master/templates/Main.elm).

**Comment by mgold** [comment]
Actually I'm going to reopen until @udnisap confirms the fix worked.

**Comment by udnisap** [comment]
Yes It works. Thanks @mgold 
Should we add it to Readme when migrating to 0.18?

**Comment by mgold** [comment]
Done.
