### ISSUE TITLE
Split fuzz out into another library

### ISSUE THREAD

**Issue by eeue56** [elm-community/elm-test#82]
While elm-check exists, ideally, there should be a way to use fuzz without needing to use elm-test. Generating random values in the way that fuzz does is not limited to testing only.

Specifically: we need it for elm-doc-test.

**Comment by mgold** [comment]
Can you tell me more about elm-doc-test and why it can't be used with elm-test?

**Comment by eeue56** [comment]
It can. We need the generators for [this](https://github.com/stoeffel/elm-doc-test/issues/2#issuecomment-261804622)

**Comment by mgold** [comment]
Since you yourself say that "generators in doctests should probably be discouraged", why should we break them out for that library?

And, since you're generating tests anyway, can't you generate tests that invoke fuzzers when run without having the fuzzers when you generate? And if you did need them, couldn't you import them from elm-test, since it's effectively a dependency anyway?

I'm sorry to push back on this, but my concerns are (1) it would add another dependency in a long chain that's a pain to update with every release of Elm and (2) it would make the docs for fuzzers much harder to find.

**Comment by eeue56** [comment]
> And, since you're generating tests anyway, can't you generate tests that invoke fuzzers when run without having the fuzzers when you generate? And if you did need them, couldn't you import them from elm-test, since it's effectively a dependency anyway?

The point is to not generate tests, it's to generate a range of shrinked fuzz values to help the user end up on the best examples to catch edge cases. It's up to the user - not elm-test.

> I'm sorry to push back on this, but my concerns are (1) it would add another dependency in a long chain that's a pain to update with every release of Elm and (2) it would make the docs for fuzzers much harder to find.

1) It's either that or have it forked and pulled out, and miss out on bug fixes and improvements from not using the dep
2) is a solvable concern - just re-expose things as part of elm-test. Fuzz is for library developers and tooliing, elm-test is for users.

**Comment by zkessin** [comment]
Is there any reason that another library can't just use the fuzzers from Elm test even if they don't use them for testing?

**Comment by mgold** [comment]
That's not a bad idea - expose some kind of interface to use the fuzzers, for expert cases like this one.

**Comment by eeue56** [comment]
@zkessin there is no way to generate or access them without using elm-test and generating a test

**Comment by mgold** [comment]
Right, I'm suggesting we could add one, perhaps
```elm
runFuzzer : (a -> Bool) -> Fuzzer a -> Random.Generator (Maybe a)
```

You would supply a fuzzer and a function that should always return `True`. Then you can generate either `Just` a small value that makes the function `False`, or `Nothing` if no such value was found.

Would this or some variation be useful?

**Comment by eeue56** [comment]
That API doesn't make a bunch of sense to me. Why provide the a -> Bool externally?

**Comment by mgold** [comment]
If you just want `f : Fuzzer a -> Generator a`, that's easy to accomplish. I had assumed you wanted some kind of shrinking, which is the reason for the function - shrinking requires knowing whether a shrunken value also replicates the behavior (e.g. a failing test).

**Comment by eeue56** [comment]
Nope - sorry, I just needed the purpose to the `a -> Bool` function. That sounds like it will work for me

**Comment by mgold** [comment]
Okay, I'll try to get a PR with an implementation of `runFuzzer` up in the next few days.

**Comment by rtfeldman** [comment]
If we do a separate package, it's either going to be a worse UX for users (having to go to a different package to find the docs) or else if we go the "re-export aliases" route, we'll have to manually keep the docs in sync between the two packages - which we will probably mess up on a regular basis.

@eeue56 thoughts on just exposing `runFuzzer`?

**Comment by mgold** [comment]
> That sounds like it will work for me

I *think* "that" refers to exposing `runFuzzer`, which is why I offered to implement it.

**Comment by rtfeldman** [comment]
Ah, gotcha!

**Comment by mgold** [comment]
So I totally dropped the ball on implementing `runFuzzer`... do you still need it?

**Comment by eeue56** [comment]
Yes, still need it. Just had more pressing things to work on

**Comment by mgold** [comment]
Tagging help wanted, mostly to remind me to do it.

**Comment by mgold** [comment]
After trying to implement this and reading [this thread](https://groups.google.com/forum/#!topic/elm-discuss/mFF08xSz4cE), I think this would be a better interface:

```elm
type Shrinkable a = <opaque>

fuzz : Fuzzer a -> Random.Generator (a, Shrinkable a)

shrink : Bool -> Shrinkable a -> Maybe (a, Shrinkable a)
```

Names subject to change and suggestions, but I'd like to place this in `Test.Runner` to emphasize that it's for expert use.

The idea is that you can always get some value. If that value makes you test fail, you can ask for a shrunken value. If the value does not make your test fail, but it's shrunken from one that does, there may be some alternate shrinking that *does* make your test fail -- so you can ask for that.

Seem okay to everyone?

**Comment by rtfeldman** [comment]
Makes sense to me!
