### ISSUE TITLE
After upgrade, failing tests don't display in console output

### ISSUE THREAD

**Issue by ckoster22** [elm-community/elm-test#84]
I recently upgraded from Elm 0.17 to 0.18 and now I'm on elm-test 3.*

When running tests on the command line I no longer see the reason for why a failed test actually failed. This problem can be reproduced by making one of the examples tests in the README fail on purpose.

For example, I changed the following test:

```
test "reverses a known string" <|
                \() ->
                    "ABCDEFG"
                        |> String.reverse
                        |> Expect.equal "GFEDCBAasdf"
```

This is the output I saw:

```
Success! Compiled 1 module.                                         
Successfully generated /var/folders/kj/9crr77vn1cn02r717v7dvqy80000gn/T/elm_test_1161024-7165-shea92.js

TEST RUN FAILED

Duration: 27 ms
Passed:   2
Failed:   1
```

I remember before upgrading that I would see an expected/actual message in the console output and which test failed. I no longer see that.

**Comment by mgold** [comment]
`npm update -g elm-test`
