### ISSUE TITLE
No details when a test fails

### ISSUE THREAD

**Issue by tomphp** [elm-community/elm-test#86]
Hi,

When I run `elm-test` I'm getting output which looks like this

```
Success! Compiled 2 modules.
Successfully generated /var/folders/g9/bfbr50nj0t71kspl97pvfflm0000gn/T/elm_test_116112-4570-3mboiy.js

TEST RUN FAILED
Duration: 89 ms
Passed:   9
Failed:   1
```

It tells me how many tests have passed and failed, but it doesn't show which test/expectation failed. How do I get that information?

Thanks

**Comment by rtfeldman** [comment]
I've seen this happen when running 0.18 tests using an older version of the
elm-test binary...can you re-run npm install -g elm-test and see if that
fixes it?

**Comment by tomphp** [comment]
@rtfeldman Thank seems to have fixed it. Thanks for the suggestion! 👍
