### ISSUE TITLE
Passing `[]` to `describe` should be a failed test

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/elm-test#95]
If I pass `[]` to `describe`, then I either made a mistake or I am leaving it as a placeholder while I sketch out the structure of my tests.

In either case, if I pass `[]` to `describe` then it means I have more work to do (either fixing the mistake or implementing the tests), and it makes the most sense to have it fail the test run so I can't forget.

This should be a breaking change even though the API would be the same.

**Comment by mgold** [comment]
There's no way to make a release *more* major than it should be, so this would have to wait until we'd need a major release anyway. Also, I'm not sure I agree entirely with the logic since there's no valid use case here, i.e. no one does this permanently intentionally, and we're just detecting a bug.

**Comment by rtfeldman** [comment]
That's a fair point.

You can make an intentionally breaking release by adding something like "deleteMeToBump" as minor, then deleting it to publish as major, but yeah. I suppose this could arguably be a patch.

**Comment by mgold** [comment]
> You can make an intentionally breaking release by adding something like "deleteMeToBump" as minor, then deleting it to publish as major

ewww....

**Comment by mgold** [comment]
We should probably add an "empty list" case to the `Reason` type and use it for `Expect.all` too.

**Comment by rtfeldman** [comment]
Yep, good point!

**Comment by mgold** [comment]
I went to implement this and found myself wanting some of what I implemented in #96 so I think we should wait until that's merged. I don't think that's blocking on anything.
