### ISSUE TITLE
Fuzzers break when given aliased alias

### ISSUE THREAD

**Issue by j-panasiuk** [elm-community/elm-test#98]
I'm trying to create custom fuzzer for an aliased 3rd party type. When that imported type happens to be type alias itself, things break. Actually I ran into this using my own alias for `Window.Size` (This is not a big issue in this case, since I can just stick to using original types and avoid this problem altogether. But it leaves me confused about how aliasing really works...)

```elm
import Fuzz exposing (Fuzzer)
import Random.Pcg as Random exposing (Generator)
import Shrink exposing (Shrinker)


type alias Finding =
    { value : Int }


type alias Trap =
    Finding


itsATrap : Fuzzer Trap
itsATrap =
    let
        generator : Generator Trap
        generator =
            Random.map Trap (Random.int 0 100)

        shrinker : Shrinker Trap
        shrinker { value } =
            Shrink.map Trap (Shrink.int value)
    in
        Fuzz.custom generator shrinker

```
produces
```
-- NAMING ERROR ------------------------------------------------ ././Fuzzers.elm

Cannot find variable `Trap`

23|             Random.map Trap (Random.int 0 100)
                           ^^^^
Maybe you want one of the following?

```
as well as
```
-- NAMING ERROR ------------------------------------------------ ././Fuzzers.elm

Cannot find variable `Trap`

27|             Shrink.map Trap (Shrink.int value)
                           ^^^^
Maybe you want one of the following?

```
Substituting `Trap` with `Finding` solves the problem, and quick REPL check confirms that it must be a problem with aliasing another type alias. This surprises me, because

1.  I've been using this type all over the place in type signatures and nothing suspicious ever happened
2.  all tutorials/docs I've seen claim that type alias is just a convenience thing used for readability and doesn't differ from original otherwise. But it seems like using an alias twice makes the new type somehow misplace its constructor!

Should this be an issue on the compiler? Or does the type system just behave this way, only the error message could be improved here?

**Comment by mgold** [comment]
This is a [known issue with the compiler](https://github.com/elm-lang/elm-compiler/issues/1019). It is not a type problem. Rather, the definition of `Finding` creates, in addition to the type, the "record constructor" function `Finding : Int -> Finding`.

The alias of `Trap` creates the type alias just fine, but not the record constructor.

This is not a bug in elm-test, or any library that it depends on.

**Comment by j-panasiuk** [comment]
I didn't know if it was a known problem or not. You're right it doesn't belong here
Thanks for clearing that up! (and sorry for the trouble) :)
