### ISSUE TITLE
Just a question for possible feature: nodejs memory leak testing

### ISSUE THREAD

**Issue by Rolograaf** [elm-community/elm-test#99]
Would it be possible/desirable/viable to have something like this integrated?

Are leaks coders' or compilers' problem in elm?

From @andywer  https://t.co/wC7Qq6nSI6

**Comment by avanslaars** [comment]
That work was actually done by @andywritescode (andywer on github -
https://github.com/andywer)

He tagged me in the tweet because I had asked him to let me know when he
released something.

**Comment by Rolograaf** [comment]
@avanslaars  sorry about that: I used the text of the tweet to avoid typing on my tablet, corrected it as soon as I found out.

**Comment by avanslaars** [comment]
Thanks! I certainly don't want to get credit for work I didn't do :)

This is an interesting question though. My first instinct with this would
be that any potential memory leaks in elm should be handled by the runtime,
but maybe not.

Does anybody have any elm code that causes a memory leak consistently?

**Comment by eeue56** [comment]
Sorry, I don't understand what this issue is about? Why is this on elm-test?

**Comment by mgold** [comment]
> Would it be possible/desirable/viable to have something like this integrated?

No, because...

> Are leaks coders' or compilers' problem in elm?

Leaks are most definitely compiler bugs.

But thanks for the question!
